window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-01-19T10:38:42.450277",
    "main_index": 8.11,
    "status": "CRITICAL",
    "active_scan": true,
    "next_update": "2026-01-19T11:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 3.75,
      "raw_score": 10.76,
      "events": [
        {
          "title": "“Zabel in Exile” revives Yesayan’s brave message on stage",
          "translated_title": "“Zabel in Exile” revives Yesayan’s brave message on stage",
          "link": "https://armenianweekly.com/2026/01/17/zabel-in-exile-revives-yesayans-brave-message-on-stage/",
          "date": "Sat, 17 Jan 2026 16:33:59 +0000",
          "category": "violent protest",
          "confidence": 0.9765116572380066,
          "weight": 6.835581600666046,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.7%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Armenia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Armenia’s Government Scolds Skier Who Refused To Promote Azerbaijan - Oragark",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNRFZyby1Za1JPU1FXRHZXaFVHcno2VEh4dWk0b1BiZkVRVExuVDhhN0szR1RzTldIYVJLYjRlMFFjZ2ZZanJ1bUVSR3Z6TmhmWjJpOFBBcVh4NFVmeFJSZm1OUEQyTVFlS0dJbVRRdmloZWxJVHdnTnoxdkIwZmNjUVUwTWtmNmwzNnNsTXdlUUpTaV94ZkE?oc=5",
          "date": "Mon, 19 Jan 2026 10:18:58 GMT",
          "category": "political crisis",
          "confidence": 0.7450469136238098,
          "weight": 4.470281481742859,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "74.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Iranian protesters in Yerevan blocked from march as police make arrests",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/18/iranian-protesters-in-yerevan-blocked-from-march-as-police-make-arrests/",
          "date": "Sun, 18 Jan 2026 13:19:09 +0000",
          "category": "violent protest",
          "confidence": 0.6320260167121887,
          "weight": 4.424182116985321,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "63.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Aleppo and the collapse of a shared future",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/18/aleppo-and-the-collapse-of-a-shared-future/",
          "date": "Sun, 18 Jan 2026 14:29:22 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.32351788878440857,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "When diaspora and diplomacy cross wires",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/18/when-diaspora-and-diplomacy-cross-wires/",
          "date": "Sun, 18 Jan 2026 14:00:40 +0000",
          "category": "political crisis",
          "confidence": 0.2061741203069687,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armen Aroyan, diasporan guide and chronicler of Armenian ancestral memory, dies at 82",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/armen-aroyan-diasporan-guide-and-chronicler-of-armenian-ancestral-memory-dies-at-82/",
          "date": "Sat, 17 Jan 2026 20:10:31 +0000",
          "category": "violent protest",
          "confidence": 0.2413245290517807,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Arlington Philharmonic Orchestra presents “A Mid-Winter Concert: Armenia”",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/arlington-philharmonic-orchestra-presents-a-mid-winter-concert-armenia/",
          "date": "Sat, 17 Jan 2026 16:01:46 +0000",
          "category": "violent protest",
          "confidence": 0.17967653274536133,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "ANCA Nationwide Townhall to rally community behind 2026 advocacy and electoral priorities",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/anca-nationwide-townhall-to-rally-community-behind-2026-advocacy-and-electoral-priorities/",
          "date": "Sat, 17 Jan 2026 15:09:52 +0000",
          "category": "political crisis",
          "confidence": 0.31638216972351074,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "“Celebrate Armenia!” virtual program highlights schools and youth programs in Greater Boston",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/celebrate-armenia-virtual-program-highlights-schools-and-youth-programs-in-greater-boston/",
          "date": "Sat, 17 Jan 2026 15:00:55 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.29480084776878357,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "ALC executive director Siranush Sahakyan calls prisoner release a “transactional” deal",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/alc-executive-director-siranush-sahakyan-calls-prisoner-release-a-transactional-deal/",
          "date": "Sat, 17 Jan 2026 14:59:10 +0000",
          "category": "neutral news",
          "confidence": 0.36663663387298584,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "36.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Delal Dink to deliver memorial lecture at Harvard University",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/17/delal-dink-to-deliver-memorial-lecture-at-harvard-university/",
          "date": "Sat, 17 Jan 2026 14:19:19 +0000",
          "category": "neutral news",
          "confidence": 0.24630920588970184,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "\"Celebrate Armenia!” virtual program highlights schools and youth programs in Greater Boston - The Armenian Weekly",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMixwFBVV95cUxOY1RlQzlZLUZTaFY0WVh1TGZxbVR2STNwZ2VBaF8wVjZtYmprT0pYUWVGa25EVjUzb3M1QkJmQ2Jody12dUc0TFNJTjNwZlBhVnB2eFJDNjdaYkpzLTNlRk1qRldPcG01ZGtUN19yeWNrTjUyZXc5UE9ORndGWlhBSWY3WGJFNXQ4eGd3TEZLcC0wRkFuNko5ZEg1VmN2dm9qSDBQZGNoX0ViMlM5SUNaNFBpN0V2eDdiN0JCWGFhOVlNbFpPRDRF?oc=5",
          "date": "Sat, 17 Jan 2026 15:48:54 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.24492275714874268,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The TRIPP Implementation Framework: Not Capitulation- But Not Protection Either - Hetq.am",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE9OVUo5d3ZVdmZWSjkxenJNV3ltZHhfRHRNV3R4cWloUjVfRjZGWjdHalVqR2dIR1pmUEVzYlFBaWlianN0MEhUbA?oc=5",
          "date": "Mon, 19 Jan 2026 08:01:00 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.6778331398963928,
          "weight": -1.3556662797927856,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "67.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The TRIPP Implementation Framework: Not Capitulation- But Not Protection Either",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179294",
          "date": "Mon, 19 Jan 2026 12:01:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.819525957107544,
          "weight": -1.639051914215088,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "82.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "US takes lead in Caucasus peace deal as France is pushed aside - RFI",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNRHJ0dl9RQjUwU0NiYmk2U3ZuNzRpRHREVXg1V3lpTUhQUVNOWHUyUWdoWEo3aE9pQlBWS2RlQVMzNkZPYTdYMFh0TEVFZ2NqS2hPdUNmTFpIYVlYNXRPUHZCaU5xVk13bjltTHFkN2hpMWZKR3FCRVg4cmQ4YmhUWVctNFVVTzQwWVk1cU5LVjZEb1A3WHVRZVdKaThGRjRQVEM3ZklaOExkQlU?oc=5",
          "date": "Sat, 17 Jan 2026 15:07:03 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.9872135519981384,
          "weight": -1.9744271039962769,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "98.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 5.02,
      "raw_score": 26.25,
      "events": [
        {
          "title": "Georgia man arrested after shouting N-word at security - Rolling Out",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMie0FVX3lxTE0zVk9Wb2RBSFpqdEtiOFVmQWJZZXM3Qk8tZzljX3FhZm9wWE55Ni1zOUg4SGNOR2d6NzRONzNhX3FLRE83Y1JVYWJ3bDI5ejNpdnJJUkgtN044UnI2dEs4ck1jMmZCUUhxM0FENEZITUY0ZXVTNXV2WVU0UQ?oc=5",
          "date": "Sat, 17 Jan 2026 14:28:41 GMT",
          "category": "violent protest",
          "confidence": 0.7913482189178467,
          "weight": 5.539437532424927,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "79.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "‘Calm him down’: the culture of obstruction facing political prisoners like me in Azerbaijan",
          "translated_title": null,
          "link": "https://oc-media.org/calm-him-down-the-culture-of-obstruction-facing-political-prisoners-like-me-in-azerbaijan/",
          "date": "Mon, 19 Jan 2026 07:48:22 +0000",
          "category": "political crisis",
          "confidence": 0.916587769985199,
          "weight": 5.499526619911194,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "91.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "The Meydan TV trial continues in Azerbaijan as one of the arrested journalists goes on hunger strike",
          "translated_title": null,
          "link": "https://jam-news.net/meydan-tv-trial-in-azerbaijan-continues-arrested-journalist-goes-on-hunger-strike/",
          "date": "Sat, 17 Jan 2026 11:26:10 +0000",
          "category": "violent protest",
          "confidence": 0.680687665939331,
          "weight": 4.764813661575317,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "German Ambassador in Georgia and a ‘secret meeting’: pro-government media attempt to discredit diplomat",
          "translated_title": null,
          "link": "https://jam-news.net/georgian-authorities-accuse-german-envoy-media-attempt-to-discredit-diplomat/",
          "date": "Sat, 17 Jan 2026 15:13:29 +0000",
          "category": "political crisis",
          "confidence": 0.7190239429473877,
          "weight": 4.314143657684326,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "71.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia Sees Nearly 7 Million International Visits in 2025, Most From Russia",
          "translated_title": null,
          "link": "https://civil.ge/archives/717769",
          "date": "Sun, 18 Jan 2026 12:12:07 +0000",
          "category": "violent protest",
          "confidence": 0.45992493629455566,
          "weight": 3.2194745540618896,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "46.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Unfriending Europe: How Georgian Dream Turned its Rhetoric against the EU - Civil Georgia",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE1qYnF2MXdiTjNRV2VvMjJ1QnptSkg2eGd2MlZVNWtnZkoyc2tPYkMwQklNcjl5QWJ3S2hFT0l5bXRramNJX2Vv0gFMQVVfeXFMT3k4QWVDSEM0T1FSMldVczNVdTlpOGotRzh6QUIwMTJEWTlPWUo0SElqU3dsVk5kQWt6NUdPU0FrbXVfc1NDSGYxcm9CbA?oc=5",
          "date": "Sun, 18 Jan 2026 12:21:43 GMT",
          "category": "political crisis",
          "confidence": 0.48602548241615295,
          "weight": 2.9161528944969177,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "48.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Madeira Joins Portugal, Tbilisi, Georgia, Chicago, Quy Nhon, Vietnam, Puerto Escondido and Mexico in Becoming New Travel Destinations in 2026 - Travel And Tour World",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikgJBVV95cUxOOVd1ODNaeVUybUw5bURRUmFNSVZ0bXhJVlNMUEhzaXNZeHVmLVlqSExoc0M0WnhBMkFoeWVZNDZ1WlVVZlNPQ2FWelp2RUdEeFRhREpWenQySUdVNUlfWHloOFpHa29qU2V3NFZ4eWpQem0taVNDV3Nic0lBT0J6RjZUS1B0aWUxQmFEem1aNjJ1UTIyU1dXWkZfTl9OOVhxOFRtUzFaaGJ4bWtTYWF4Z193bUZCRFZ3UFFGNDhKXzhJb2l4elRodXVJOFY4Sm1zeWZPQUNzd2JfSXpDd1hRM1lIX1RwR1E0UHppTGZGY2JaM2kxSEZubHhQNlRCNFc5djM1NVk0cWdFNTZXTDEzb2dB?oc=5",
          "date": "Mon, 19 Jan 2026 02:41:16 GMT",
          "category": "violent protest",
          "confidence": 0.3300808072090149,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia Sees Nearly 7 Million International Visits in 2025, Most From Russia - Civil Georgia",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE5BaG1VYkNzOXg0aTUxS2F4UGJPMUJkZF9ONTB0LW5JQURndGoyRGswTUxJWXA4LTZHRWlVMmR5eVlnZlZNTVZZ0gFMQVVfeXFMTjFYNHRtdmotNEZmb2VCLW9zNVllWmVDWjROUDZFMEpSTlY2dmhDS2pfaGhMaTVFd0QxbTNXdWp3bVQtYTRNdDRZanA4Rg?oc=5",
          "date": "Sun, 18 Jan 2026 12:12:07 GMT",
          "category": "violent protest",
          "confidence": 0.3414888083934784,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "34.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Unfriending Europe: How Georgian Dream Turned its Rhetoric against the EU",
          "translated_title": null,
          "link": "https://civil.ge/archives/717831",
          "date": "Sun, 18 Jan 2026 12:21:43 +0000",
          "category": "political crisis",
          "confidence": 0.3861196041107178,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Pro-GD Media Claim German Ambassador Pushed ‘Iranian Scenario’ in ‘Secret’ Meeting with Youth",
          "translated_title": null,
          "link": "https://civil.ge/archives/717795",
          "date": "Sat, 17 Jan 2026 14:34:29 +0000",
          "category": "neutral news",
          "confidence": 0.49022209644317627,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "49.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Monday, 19 January 2026",
          "translated_title": null,
          "link": "https://oc-media.org/monday-19-january-2026/",
          "date": "Mon, 19 Jan 2026 08:47:32 +0000",
          "category": "neutral news",
          "confidence": 0.2512282729148865,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "11 Best Places To Retire In Georgia - WorldAtlas",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMihgFBVV95cUxPQlpBTHVzUTlaN0JBTEhBMlhyeXYtT2htTWdDdmtZdnY4cW9LaEVFbzN2dW1YOTMzMDMtYTNiMFNyYUxhM0swamg1aHFuODhxQVl3MDRRcXN6UkwyOTkxS3p5bDVLaENiM0hsVDZDZllSbWxTSWtFUXFBa3FSLVEyX2NqbHZkdw?oc=5",
          "date": "Sun, 18 Jan 2026 18:00:00 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.24696862697601318,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Latest news in Georgia, Armenia, Azerbaijan, summary. Live",
          "translated_title": null,
          "link": "https://jam-news.net/news-from-georgia-azerbaijan-armenia-19-23-january-2026/",
          "date": "Mon, 19 Jan 2026 04:37:41 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.20268619060516357,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Fox News: “Georgian demonstrators watch Iran closely as their own protests grind on”",
          "translated_title": null,
          "link": "https://jam-news.net/fox-news-compares-protests-in-georgia-and-iran/",
          "date": "Sun, 18 Jan 2026 09:31:42 +0000",
          "category": "political crisis",
          "confidence": 0.4091297388076782,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "40.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "“We have mutually closed the page of enmity”: Armenian Parliament Speaker on relations with Turkey",
          "translated_title": null,
          "link": "https://jam-news.net/we-have-mutually-closed-the-page-of-enmity-armenian-speaker-on-relations-with-turkey-and-azerbaijan/",
          "date": "Sat, 17 Jan 2026 12:10:18 +0000",
          "category": "neutral news",
          "confidence": 0.2713819146156311,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 3.26,
      "raw_score": 7.54,
      "events": [
        {
          "title": "The Current US Political Climate Is Spurring a ‘Reclaim’ and Rallying on the MLK Holiday",
          "translated_title": "The Current US Political Climate Is Spurring a ‘Reclaim’ and Rallying on the MLK Holiday",
          "link": "https://www.thenationalherald.com/the-current-us-political-climate-is-spurring-a-reclaim-and-rallying-on-the-mlk-holiday/",
          "date": "Mon, 19 Jan 2026 04:00:48 +0000",
          "category": "political crisis",
          "confidence": 0.9886420965194702,
          "weight": 5.931852579116821,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "98.9%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Greece",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "DOJ Vows To Press Charges After Activists Disrupt Church Where Minnesota ICE Official Is a Pastor",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/doj-vows-to-press-charges-after-activists-disrupt-church-where-minnesota-ice-official-is-a-pastor/",
          "date": "Mon, 19 Jan 2026 02:38:29 +0000",
          "category": "violent protest",
          "confidence": 0.6161096096038818,
          "weight": 4.312767267227173,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "61.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Μάριος Πλωρίτης: ΗΠΑ, οι αυτόκλητοι «σωτήρες της ανθρωπότητος»",
          "translated_title": null,
          "link": "https://www.in.gr/2026/01/19/istoriko-arxeio/marios-ploritis-ipa-oi-aytoklitoi-sotires-tis-anthropotitos/",
          "date": "Mon, 19 Jan 2026 12:24:21 +0300",
          "category": "humanitarian crisis",
          "confidence": 0.7765151262283325,
          "weight": 2.3295453786849976,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "77.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "China’s Population Falls Again As Births Drop 17% a Decade After the 1-Child Policy Ended",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/chinas-population-falls-again-as-births-drop-17-a-decade-after-the-1-child-policy-ended/",
          "date": "Mon, 19 Jan 2026 04:50:41 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.24692034721374512,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Luka, LeBron Get the Lakers Back Into Form in a 110–93 Victory Over the Raptors",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/luka-lebron-get-the-lakers-back-into-form-in-a-110-93-victory-over-the-raptors/",
          "date": "Mon, 19 Jan 2026 04:45:38 +0000",
          "category": "violent protest",
          "confidence": 0.2638895809650421,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "China’s Economy Grows 5% in 2025, Buoyed by Strong Exports Despite Trump’s Tariffs",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/chinas-economy-grows-5-in-2025-buoyed-by-strong-exports-despite-trumps-tariffs/",
          "date": "Mon, 19 Jan 2026 04:43:52 +0000",
          "category": "neutral news",
          "confidence": 0.23696722090244293,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Durant Moves Past His ‘Idol,’ Dirk Nowitzki, Into 6th Place on the NBA’s Career Scoring List",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/durant-moves-past-his-idol-dirk-nowitzki-into-6th-place-on-the-nbas-career-scoring-list/",
          "date": "Mon, 19 Jan 2026 04:00:21 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.33857327699661255,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "NFL Again Faces Questions About the Definition of a Catch After Disputed Pick in Bills-Broncos Game",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/nfl-again-faces-questions-about-the-definition-of-a-catch-after-disputed-pick-in-bills-broncos-game/",
          "date": "Mon, 19 Jan 2026 03:20:26 +0000",
          "category": "violent protest",
          "confidence": 0.18425151705741882,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "At 45, Venus Williams Sets Record at Australian Open but Falls in the 1st Round",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/at-45-venus-williams-sets-record-at-australian-open-but-falls-in-the-1st-round/",
          "date": "Mon, 19 Jan 2026 02:29:29 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.22946569323539734,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Small Part of Sunshine State Becomes Snowy State As Florida Gets Snow Second Year in a Row",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/small-part-of-sunshine-state-becomes-snowy-state-as-florida-gets-snow-second-year-in-a-row/",
          "date": "Mon, 19 Jan 2026 00:30:04 +0000",
          "category": "neutral news",
          "confidence": 0.30213382840156555,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "EU Officials at the Green Line Experience the Turkish Occupation of Cyprus",
          "translated_title": null,
          "link": "https://www.thenationalherald.com/eu-officials-at-the-green-line-experience-the-turkish-occupation-of-cyprus/",
          "date": "Sun, 18 Jan 2026 20:01:25 +0000",
          "category": "neutral news",
          "confidence": 0.239696204662323,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Kόντρα στην Ιταλία για την πρόκριση στα ημιτελικά – Η προϊστορία εις βάρος της Ελλάδας",
          "translated_title": null,
          "link": "https://www.in.gr/2026/01/19/sports/othersports/kontra-stin-italia-gia-tin-prokrisi-sta-imitelika-proistoria-eis-varos-tis-elladas/",
          "date": "Mon, 19 Jan 2026 12:26:21 +0300",
          "category": "military conflict",
          "confidence": 0.2387470155954361,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Αιτωλοακαρνανία: Απολογείται την Τετάρτη ο δράστης του φονικού – Τι ισχυρίζεται",
          "translated_title": null,
          "link": "https://www.in.gr/2026/01/19/greece/aitoloakarnania-apologeitai-tin-tetarti-o-drastis-tou-fonikou-ti-isxyrizetai/",
          "date": "Mon, 19 Jan 2026 12:20:58 +0300",
          "category": "terrorist act",
          "confidence": 0.2742048501968384,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Σιδηροδρομικό δυστύχημα στην Ισπανία: Τι γνωρίζουμε μέχρι τώρα",
          "translated_title": null,
          "link": "https://www.in.gr/2026/01/19/world/sidirodromiko-dystyxima-stin-ispania-ti-gnorizoume-mexri-tora/",
          "date": "Mon, 19 Jan 2026 12:20:45 +0300",
          "category": "neutral news",
          "confidence": 0.2454816699028015,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ιαπωνία: Στις 8 Φεβρουαρίου οι πρόωρες βουλευτικές εκλογές",
          "translated_title": null,
          "link": "https://www.in.gr/2026/01/19/world/iaponia-stis-8-fevrouariou-oi-proores-vouleytikes-ekloges/",
          "date": "Mon, 19 Jan 2026 12:11:08 +0300",
          "category": "political crisis",
          "confidence": 0.347927451133728,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "34.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 5.94,
      "raw_score": 48.84,
      "events": [
        {
          "title": "SDF reports 'intense clashes' as Syrian army advances in Aleppo and Raqqa",
          "translated_title": "SDF reports 'intense clashes' as Syrian army advances in Aleppo and Raqqa",
          "link": "https://www.middleeasteye.net/news/sdf-reports-intense-clashes-syrian-army-advances-aleppo-raqqa",
          "date": "Sat, 17 Jan 2026 16:46:54 +0000",
          "category": "military conflict",
          "confidence": 0.987435519695282,
          "weight": 9.87435519695282,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "98.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Syrian government and SDF agree ceasefire after heavy fighting in northeast",
          "translated_title": "Syrian government and SDF agree ceasefire after heavy fighting in northeast",
          "link": "https://www.middleeasteye.net/news/syrian-army-gains-ground-kurdish-forces-withdraw-key-oil-field",
          "date": "Sun, 18 Jan 2026 11:26:52 +0000",
          "category": "military conflict",
          "confidence": 0.8643885850906372,
          "weight": 8.643885850906372,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "86.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Syria: SDF left weakened, short of territory and oil after ceasefire, experts say",
          "translated_title": "Syria: SDF left weakened, short of territory and oil after ceasefire, experts say",
          "link": "https://www.middleeasteye.net/news/syria-ceasefire-leaves-sdf-weakened-short-territory-and-oil-say-experts",
          "date": "Sun, 18 Jan 2026 22:07:12 +0000",
          "category": "military conflict",
          "confidence": 0.8599045872688293,
          "weight": 8.599045872688293,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "86.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran’s supreme leader says 'thousands killed' in unrest, blames Trump and Israel",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/irans-supreme-leader-says-thousands-killed-unrest-blames-trump-and-israel-1",
          "date": "Sat, 17 Jan 2026 17:53:27 +0000",
          "category": "political crisis",
          "confidence": 0.9624482989311218,
          "weight": 5.774689793586731,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Will China come to Iran's aid if war breaks out?",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/opinion/will-china-come-iran-aid-if-war-breaks-out",
          "date": "Sun, 18 Jan 2026 17:19:40 +0000",
          "category": "political crisis",
          "confidence": 0.915440022945404,
          "weight": 5.492640137672424,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "91.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Syrian Kurds seek constitutional recognition after rights decree",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/syrian-kurds-seek-constitutional-recognition-after-rights-decree",
          "date": "Sat, 17 Jan 2026 15:06:10 +0000",
          "category": "political crisis",
          "confidence": 0.834263801574707,
          "weight": 5.005582809448242,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "83.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iranian official says at least 5,000 killed in protests",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/iranian-official-says-least-5000-killed-protests",
          "date": "Sun, 18 Jan 2026 11:15:24 +0000",
          "category": "political crisis",
          "confidence": 0.64866042137146,
          "weight": 3.8919625282287598,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "64.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "‘When will Baba come back?’ Gaza's widows and orphans struggle to survive",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/when-will-baba-come-back-gazas-widows-and-orphans-struggle-survive",
          "date": "Mon, 19 Jan 2026 08:45:26 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.822359025478363,
          "weight": 2.467077076435089,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "82.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Libya signs $2.7bn deal to expand Misurata Free Zone, in diversification push",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/libya-signs-27bn-deal-expand-misurata-free-zone-diversification-push",
          "date": "Sun, 18 Jan 2026 21:53:49 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.31421875953674316,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Jerusalem Christian leaders warn against Christian Zionist 'interference'",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/jerusalem-christian-leaders-warn-against-christian-zionist-interference",
          "date": "Sun, 18 Jan 2026 14:06:25 +0000",
          "category": "terrorist act",
          "confidence": 0.2586532533168793,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump wants nations to pay $1bn to join Gaza 'Board of Peace': report",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/trump-wants-nations-pay-1bn-join-gaza-board-peace-report",
          "date": "Sun, 18 Jan 2026 10:43:10 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.3870603144168854,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Displaced northerners 'feel safer' in south Yemen after STC withdrawal",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/displaced-northerners-feel-safer-south-yemen-after-stc-withdrawal",
          "date": "Sun, 18 Jan 2026 10:21:21 +0000",
          "category": "neutral news",
          "confidence": 0.37827789783477783,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "37.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "New York pension fund may invest in Israel despite Gaza genocide, defying Mamdani",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/new-york-pension-fund-may-invest-israel-despite-gaza-genocide-defying-mamdani",
          "date": "Sat, 17 Jan 2026 21:10:16 +0000",
          "category": "military conflict",
          "confidence": 0.5303192138671875,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "53.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump appoints Tony Blair to Gaza 'Board of Peace'",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/trump-appoints-tony-blair-gaza-board-peace",
          "date": "Sat, 17 Jan 2026 10:58:24 +0000",
          "category": "neutral news",
          "confidence": 0.25226515531539917,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "How a Patrice Lumumba tribute revived pan-Africanism at Afcon",
          "translated_title": null,
          "link": "https://www.middleeasteye.net/news/how-tribute-patrice-lumumba-revived-pan-africanism-afcon",
          "date": "Sun, 18 Jan 2026 14:09:41 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.4528474509716034,
          "weight": -0.9056949019432068,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.14,
      "raw_score": 28.39,
      "events": [
        {
          "title": "Hackers hijack Iran state TV to air exiled crown prince",
          "translated_title": "Hackers hijack Iran state TV to air exiled crown prince",
          "link": "https://www.newarab.com/news/hackers-hijack-iran-state-tv-air-exiled-crown-prince",
          "date": "Mon, 19 Jan 2026 09:37:23 +0000",
          "category": "terrorist act",
          "confidence": 0.9071714878082275,
          "weight": 8.164543390274048,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "90.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Limited internet briefly returns in Iran after protest blackout",
          "translated_title": null,
          "link": "https://www.newarab.com/news/limited-internet-briefly-returns-iran-after-protest-blackout",
          "date": "Sun, 18 Jan 2026 20:42:35 +0000",
          "category": "political crisis",
          "confidence": 0.9654673933982849,
          "weight": 5.7928043603897095,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Starmer urges calm talks on Greenland after Trump tariff threat",
          "translated_title": null,
          "link": "https://www.newarab.com/news/starmer-urges-calm-talks-greenland-after-trump-tariff-threat",
          "date": "Mon, 19 Jan 2026 09:48:11 +0000",
          "category": "political crisis",
          "confidence": 0.951634407043457,
          "weight": 5.709806442260742,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Thousands march in US to back Iranian anti-government protesters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/thousands-march-us-back-iranian-anti-government-protesters",
          "date": "Mon, 19 Jan 2026 05:03:48 +0000",
          "category": "political crisis",
          "confidence": 0.8821263909339905,
          "weight": 5.292758345603943,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "88.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Surging billionaire wealth a political threat, Oxfam warns",
          "translated_title": null,
          "link": "https://www.newarab.com/news/surging-billionaire-wealth-political-threat-oxfam-warns",
          "date": "Mon, 19 Jan 2026 04:01:08 +0000",
          "category": "political crisis",
          "confidence": 0.6859411597251892,
          "weight": 4.115646958351135,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "More countries invited to Trump's Board of Peace for Gaza",
          "translated_title": null,
          "link": "https://www.newarab.com/news/more-countries-invited-trumps-board-peace-gaza",
          "date": "Mon, 19 Jan 2026 00:26:19 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.6113167405128479,
          "weight": 1.8339502215385437,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "61.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Syrian president cancels Germany visit: Berlin",
          "translated_title": null,
          "link": "https://www.newarab.com/news/syrian-president-cancels-germany-visit-berlin",
          "date": "Mon, 19 Jan 2026 04:21:22 +0000",
          "category": "political crisis",
          "confidence": 0.22690200805664062,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Socialist to face far-right candidate for Portugal's presidency",
          "translated_title": null,
          "link": "https://www.newarab.com/news/socialist-face-far-right-candidate-portugals-presidency",
          "date": "Mon, 19 Jan 2026 04:13:41 +0000",
          "category": "political crisis",
          "confidence": 0.25817206501960754,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Australian parliament holds moment of silence after Bondi attack",
          "translated_title": null,
          "link": "https://www.newarab.com/news/australian-parliament-holds-moment-silence-after-bondi-attack",
          "date": "Mon, 19 Jan 2026 03:30:14 +0000",
          "category": "violent protest",
          "confidence": 0.309621125459671,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Heckler interrupts US anthem at NBA game with Greenland protest",
          "translated_title": null,
          "link": "https://www.newarab.com/news/heckler-interrupts-us-anthem-nba-game-greenland-protest",
          "date": "Mon, 19 Jan 2026 03:16:08 +0000",
          "category": "violent protest",
          "confidence": 0.6224978566169739,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "62.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Trump admin orders 1,500 troops to prepare for possible Minnesota deployment",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-admin-orders-1500-troops-prepare-possible-minnesota-deployment",
          "date": "Mon, 19 Jan 2026 00:38:37 +0000",
          "category": "military conflict",
          "confidence": 0.26126205921173096,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Senegal stun hosts Morocco to win AFCON title",
          "translated_title": null,
          "link": "https://www.newarab.com/news/senegal-stun-hosts-morocco-win-afcon-title",
          "date": "Mon, 19 Jan 2026 00:16:44 +0000",
          "category": "military conflict",
          "confidence": 0.21004901826381683,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Europe hits back at Trump tariff threat over Greenland",
          "translated_title": null,
          "link": "https://www.newarab.com/news/europe-hits-back-trump-tariff-threat-over-greenland",
          "date": "Sun, 18 Jan 2026 17:51:47 +0000",
          "category": "violent protest",
          "confidence": 0.24351374804973602,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Syria's leader agrees truce deal with Kurds after troops advance",
          "translated_title": null,
          "link": "https://www.newarab.com/news/syrias-leader-agrees-truce-deal-kurds-after-troops-advance",
          "date": "Sun, 18 Jan 2026 19:28:27 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.603022038936615,
          "weight": -1.20604407787323,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "60.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Syrians celebrate as Sharaa agrees truce with SDF's Abdi",
          "translated_title": null,
          "link": "https://www.newarab.com/news/syrians-celebrate-sharaa-agrees-truce-sdfs-abdi",
          "date": "Mon, 19 Jan 2026 08:50:53 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.6572134494781494,
          "weight": -1.3144268989562988,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "65.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 6.36,
      "raw_score": 64.68,
      "events": [
        {
          "title": "Syrian army extends control in north, seizes oil fields - dw.com",
          "translated_title": "Syrian army extends control in north, seizes oil fields - dw.com",
          "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxPT3RHLWZ3OC0yT0JmaFMwV2l0LWJlN1pTVGQ4aV9kRUhOLTVrOGZnMXYtVEF5TmVfVExYd0hxU254Y211c0ZQRUJ5UkRWRzY3U0kySUZHUURDeEo4TUd6Q24zTENYdjB3MTZ1Qkg0aG9pQ0xaZDhsNE9YQ2pzRU55ZjVuVGFoMjVZNlBCVDZ5enA3WDJwRkHSAZYBQVVfeXFMTUlCVjFRaXZzaXo1cW9jeEFjbjB3SVdNcW1mSDA0SFNYTG1MSW40MUhZYzdRcnljcFNJd1ZTSk10aUhDWXlpS2NzWlV2cXdNZmlTeTlocnNOX21RU1NvNHIwWDlIRUc5NEpoYWdId0NWSkMxOVptaHpnc2ZoS2JZZHNvdlFiTUdhMWt2MXBpNnJIcGJqajBB?oc=5",
          "date": "Sun, 18 Jan 2026 14:34:29 GMT",
          "category": "military conflict",
          "confidence": 0.9773009419441223,
          "weight": 9.773009419441223,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian army takes control of east Aleppo towns as Kurdish fighters withdraw - Al Jazeera",
          "translated_title": "Syrian army takes control of east Aleppo towns as Kurdish fighters withdraw - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxOaVdzQkxHNmc4TmxMOFF2LXRjN1BWb0RGclFSR3J3X1U1cmVQUFd6SFZqZWhlV08wTVdaV0xaeEZmdFo1U0RtMDBMZVNvdE9pLWF4SWI4d21uUEtUOFhwbzMxbncxeV9JSGVwc2JDcFR3S0pzT3lBM0RVa1lwNVVSRWJGb1h1THk1c2E3Y3VoR3lIWDJCYjVsREZ1Z3d1SXUybndsNUJpbE1EWllzdFZaZDFQNmZPUjjSAbwBQVVfeXFMTTU2UGxLMEJTcFhIVVVCNGg1M1dlOC16ZjZzOXlzTXpfUkhrQWRDNHFOQnNaSHduSjZQaEIyR21sSzh3elNFak4zRnZUdUd0OWYtc1UtQzZBUVdXQmFreU1MYXctZFdLRVU4TnppNUZQWjZqU3k5MkcyTnNNWUlTZTkxNm5NcFkyMi1qNU1IX29zNVQxdHZDMkg3dDdjdUlrd0gtelZtMXNyQ1l0eHo2S1BoYW1WTUY5aDRBSU0?oc=5",
          "date": "Sat, 17 Jan 2026 12:50:21 GMT",
          "category": "military conflict",
          "confidence": 0.9706689119338989,
          "weight": 9.70668911933899,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian forces capture oilfields, dam as allied tribal fighters inside Raqqa - Al Jazeera",
          "translated_title": "Syrian forces capture oilfields, dam as allied tribal fighters inside Raqqa - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxNQlhHUEVxcTNMM1NBRDhQRlVKQWpseTNLUTJPR3pQaGowWE5WdmlmWWJQUHl5Rzl2azZneVV3dVUyRENVNFpGVFpBNVFNTG1ObXVyV3JIT0VyX09xY3Jfd0MyZUdrVHU0ZFRFR2Jpb3Vub1VSTmxBT3AzQ2FoaE9UbXU3U2dTcVdyT29xcXJxOXZoZlNqaHJnd1NYdnRhbVZQVURBTEdn0gGrAUFVX3lxTE9ZTGVlSlZuZnc1clpOMlZPVVlnWDhzcDNSYmkxWXp6dUNOdWxFb0I0ZXY3YTZGbUdBVTV3QnNBX1JJQ0c5dW9tWXd4RE5JMzlWdWx3MjVqQlBDaHVOa2o4RWtQZkFZd3N1dWY2cmlyMUlWa3I5WlBNa1BnaFVMREFDRU85bWQ4QzIwVWpwbDVlRlYtWVRHdkh4R3kyMjg4ZFRMTlBZeWgtZUhLRQ?oc=5",
          "date": "Sun, 18 Jan 2026 13:54:48 GMT",
          "category": "military conflict",
          "confidence": 0.955558717250824,
          "weight": 9.55558717250824,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria live: Government forces take control after heavy fighting with SDF - Al Jazeera",
          "translated_title": "Syria live: Government forces take control after heavy fighting with SDF - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMivgFBVV95cUxQSWF0ZWlnNUIwdG5EWk9jNFpVS3pkLXdYZFFHOXJ2bVBTUmV4NGZ6bFNINGxnSTJSczVNUHhnN2NEZTZObm5jc083QVplbTNZbklQRlpLQ3dUcWNYMlBxVzV1WGlnOG5rbW5RYzVPMWVvZmFMZHVCa29ibmdKY0hJcEc4LUNCUUNQQ29ON3VudWhWaWk2bEc5VklCTGs2dWVhVUk5OTRMN2FRT180dzhNbnNDbHlBQlgwSlR6RzJ30gHDAUFVX3lxTFB6MkVvelhjTWt0MDVpVVNjYUhNcWRueU0zX1RWUTBhX1NKeFhLWkI5RGFSRjB3aVRwSVVvcVpja3NfLTBMTFlMZGhnd1NMY0xna1A2RlMtWm9hSUdacVh2UWZlQjNCZUNwMnY4Um9FR3puSmVDcGJtMHBqRjV4VHpJdWZYM3M2Y21oTnQ2aEZuYVVRUndXX1RwVXV0eVRaVmVvWkVQRVg3T2lyYm1ScUZKb0NMTk5NMU9FcGsxcjhlZUpWaw?oc=5",
          "date": "Mon, 19 Jan 2026 09:56:15 GMT",
          "category": "military conflict",
          "confidence": 0.9315248727798462,
          "weight": 9.315248727798462,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Kurdish forces retreat as government troops advance across northern Syria - CNN",
          "translated_title": "Kurdish forces retreat as government troops advance across northern Syria - CNN",
          "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxQRnlkQmlUNnR2SmdreW4xRldJS3E2Q1VmWWEtYWcwWE5iN3pwRkZFVXh3UThuQmtIMWFVNWZJLVZiS19LUmpISEpySjAwXzljU1BVY212X0hzcm9DN25naDU0UUg3NmVudHB4TDFDaDFsUDJxSExIRGRvZzhoUFAxY29SUXY1VkhENmc?oc=5",
          "date": "Sat, 17 Jan 2026 13:58:13 GMT",
          "category": "military conflict",
          "confidence": 0.8675201535224915,
          "weight": 8.675201535224915,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "86.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Power lines and power struggles: Unpacking Syria’s push towards unification - Al Jazeera",
          "translated_title": "Power lines and power struggles: Unpacking Syria’s push towards unification - Al Jazeera",
          "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxQT0tGOFI5NEJXTi1xeFFQRzRRb3QzWTN0enlZdGlfZ1VqSUFqQ1ptWW1aYW5TN08yQ3oyQjQtbi1FWEJqek10NkI4NVdYVi1xcjVrNTJGRy1LTmd6cXBpTkhNaUVXNjQ2a2ZmRzBzV05zbHJlMGd0LWhWaHNOTEQ1THRsMDVVLWxTa1p3TnJZaWJzTVpDT3B0M2NYQkpmU0FDWnZIcFVQQnk2RzVnN1dpNUR5d9IBuAFBVV95cUxQNnVSZzJETXNBVnB1UDhLWWg0c01EZXRFUzY2TXpFenZNSF96V2Z1LWJCWXd4LXRwOEpxb0FRdHdMR2stRnU2dlF3V2ZqZC14YXE1N2laeDRrUmY3dVZURUphN01ua0t6YzkzVk9VWEtzOUhGeXVUbDJuMmVmSnN6OWxWcFp4eEhsa2w2RGNyZk1fOVZlZ1VycktZYjBTTWtsNDNRTHhYXzlXUlFwQjFacXVfQzM3VVZE?oc=5",
          "date": "Mon, 19 Jan 2026 10:28:31 GMT",
          "category": "political crisis",
          "confidence": 0.9895399212837219,
          "weight": 5.9372395277023315,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "99.0%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Europe’s conflict with US grows + Berlin’s Syria problem is postponed - Table.Briefings",
          "translated_title": "Europe’s conflict with US grows + Berlin’s Syria problem is postponed - Table.Briefings",
          "link": "https://news.google.com/rss/articles/CBMia0FVX3lxTE1xcHRFR015R3h6ZUdlOU5DVVVtRHZBMjZ4cURvZmxWRWh2eWpBTXhhTzNEdmhYcnJybGU2cEZYR2M4aVZHa3pxcWNVYUwwMG1BYnN1Q2F1Nmc3aHk4Wno4MmtCNVRpSVprcVhR?oc=5",
          "date": "Mon, 19 Jan 2026 04:53:09 GMT",
          "category": "political crisis",
          "confidence": 0.9770538806915283,
          "weight": 5.86232328414917,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.7%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Understanding the unfolding new power conflict in Syria - The Jerusalem Post",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE1qc2FkSEEtbnZ5X1BqX1phRUF3YnR3MEd6aUljakhSZi1sbTVVejltbWVjWEtva0Utd21DREJicTdMc2xkd1MzS1V4dEpWMGxna1hXc3psX3JHbEtQ?oc=5",
          "date": "Sun, 18 Jan 2026 16:38:45 GMT",
          "category": "political crisis",
          "confidence": 0.9275116324424744,
          "weight": 5.565069794654846,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "92.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Will Syria-Kurdish Fighting Spark Civil War in Turkey? - Middle East Forum",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxPOHczWGZUclR2bWJTRmZZWkxVNnRxLS1aU2hDVnl0NGoxcUJEWVkxODJTOGlDODdMSUtzQnlieUphYWZNVUtsYzI1aE8ycWRaZDZOSHRxdEViT09iSUdzc013bHdWNzVra0Q2SmhCckhqRkhfWHFSUUYxM3NyNW9pYkZJSG5mODV5NjM5dnpCN1RoM2Jy?oc=5",
          "date": "Sun, 18 Jan 2026 18:56:38 GMT",
          "category": "political crisis",
          "confidence": 0.7531296014785767,
          "weight": 4.51877760887146,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "75.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria updates: Government, SDF agree on immediate ceasefire - Al Jazeera",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxOZXdoUWVuVEhVMW5aZ3BoQzg3ZkhZeGF5SVFtSUdqazN5VEx0bkRkNDB2N0dWdzBXcDRjdFJuaF9RQXdlaTFEMWdYRDlnR3ZqYnZjd1lEdUpxMjVydEthMWRiN3RYRDIxcEdDbXpZQU9oOVlxVFA2ME1xZklwcnhqQy05WTR5XzhYSERNZzJFM0dDT3AzZDB4d1hrN0hSbl96T24wNXlMeHBYdHlUQkFiS25XNmlNQ0wwRDN3X3h1UdIBxAFBVV95cUxNcjlva1ZzZmp3c0RDNnhkQ1VEMTdmdDJtcGQydTRwRFVvX0tBOWtjLWlCX25SMkFpUElTdFNUeHh5bDZtNlFFZUY3MFRCcF9TLWJ6OHBoZGhiQm52N0hnNUxCLVNBQlNCRVZDaWdRTDl1VlAzU1lLSExEc3J6ZTBuelN4aGt4b1hId1BYM3U5S3MyaktxeGs3TS1pZVlFejdyZ0t0WHN0MDVBdVplbnQtdXJOR252Vmh2TlFDZHpPc3FkSzFo?oc=5",
          "date": "Sun, 18 Jan 2026 14:23:40 GMT",
          "category": "military conflict",
          "confidence": 0.5271131992340088,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "52.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria Advances on Kurdish-Held Areas as Washington Urges Restraint - The New York Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMigAFBVV95cUxPTmJtMVZKRGdJV3RtaC02SjVKR3hHaVVvV3J2TU00Wkd4Z01wa1NQYjh5YzF0dWw4Vm9RSUl3c0JEM08yM3JyOGxVcGdON2VCdl9TOFNYZGJ5OTl6SWtmSUtEOEtXcEtPX0VObXl5di1fMmhERVczQVcyRFRXdU9MWQ?oc=5",
          "date": "Sun, 18 Jan 2026 07:53:00 GMT",
          "category": "neutral news",
          "confidence": 0.3009411692619324,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s President Affirms Kurds’ Rights, in Overture to the Minority - The New York Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxOQTNLNEVHWlhnREJ3MjM5R3daZHl4M0h1UkNnUnVQMmNESUxMVjVfNG10bnRUVDlaLUtrTnNMUU5IMXdrX243UndUOUtJMUJXcDh4ZE5KclVjT2p4MGhlTU56eE15N1hCVk5ZSDRaMWxLdkpMMDdXMU9fNjVMZ1ZMeVZVdjJOREQ5dlo2N0R6UzFBVmRW?oc=5",
          "date": "Sat, 17 Jan 2026 11:54:00 GMT",
          "category": "political crisis",
          "confidence": 0.2388751357793808,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s President al-Sharaa to meet SDF leader Abdi after ceasefire deal - Al Jazeera",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisgFBVV95cUxOSVlnQklCTlRrSHhneElQb2xDa1dGNjV0anBuMzB5NTR5T2lKa2ZrYTY0aGhQVl9BLXBieG1BbTZra2FkYnhvOE1uRmtfLXdjaHpEMF9uRElRRVk1TDBpT19zTzdWV2pyRk9ycFYtV09PajV4bUxWQ1hKaU13Qi1TTllTeElVSzdhVTdKRElONFE3NjFhQUQ5SnlkQU9QTzRoNFNCaFJiTy13dmN6YndOOVhn0gG3AUFVX3lxTE0yNHBNOXhJQlE1NE55X3hCTUdJdXFVOGQ1NUM3MkxVX1FlRVpuSjVwZllXVEs5NkdZMzZzQ1d4ZEZ6UHc2eE9MTWU0M2FFYUZya2FFcTZ0d2lwWWQ3dkFvLW90TlY3dl9leklTZnUzaGw0OGFJeTRhMXhlWWh0U3lFOWVqY1RmVl9oV3ljdktxbHZQLUZSM0FuRms4Mkd6Z3RuenQxbl8tVVU0OFdKdk14R01XR1JXVQ?oc=5",
          "date": "Mon, 19 Jan 2026 09:30:21 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5651310682296753,
          "weight": -1.1302621364593506,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "56.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian government, Kurdish-led SDF agree on ceasefire: What to know - Al Jazeera",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxPY1luUlFNN1czNWx5SGJjbjRJYlVqM2lXSi1rbWFLME9ubHcwUFpsOHJzVmNEemJkUkFrN0hRMlZYVkl1TDl2Rmhrb3NYV1ZwOXp2SWQ5cFVHLXU2MnNiNGx1MnpWUEw4THZ4bDlWaDFFR1dWSnBEZXY3Z05EZThselhRbTN0X0pSMEM2cGxha2d5ektaTGtnLWZlMktnTUlvWVlINXNHblbSAa4BQVVfeXFMTkRiR0pRX2hHYlJLSHNkYWpiOVRCd1d5aEN3bnU2T0xycURyQW8wLTlqdUt4b3k0S0FvV3BoWUdxY3F1T0pfMkpHTWd5dFU1LVBjWGhQMGM4R2s1cllOVnY0dkd4SGZyRVMxUWVEUDNIeFJESXNkR2FxYnhNWV9TVWVGUDVpNVM3elcteTZYTlNRODZBQ3hKRUVtckVXbVNfWk1raklKNldTRFBBN2tR?oc=5",
          "date": "Sun, 18 Jan 2026 22:41:15 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.6712130904197693,
          "weight": -1.3424261808395386,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "67.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria, SDF agree ceasefire and integration deal - BBC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE9EaXRkbnpJd25HREpoaW5DckFFT3RvMjd2cllBNWUwQ1Z5NjhOMS10NVRsRUU3bnFUYXNxeGpWb0s2WFFub1dLTGtHVTJPaU5QakVhTTlTNXdkUdIBX0FVX3lxTE1DTzFubjRFdGpIMGJuOEVBaWdoMXFIdVpRMWhXQjFKeDFYSEZMSUFEM19EWHQ0QVV6R2VQNThVc2JITHNXbW5Ha2FfN3BIN0JPRjJHWHdxOGtvWnhZaEJF?oc=5",
          "date": "Sun, 18 Jan 2026 22:25:31 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.8793690800666809,
          "weight": -1.7587381601333618,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "87.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 3.98,
      "raw_score": 12.69,
      "events": [
        {
          "title": "Tennessee Guard participates in Bulgaria’s Best Warrior Competition - af.mil",
          "translated_title": "Tennessee Guard participates in Bulgaria’s Best Warrior Competition - af.mil",
          "link": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxNQnItcTR3cHh3eHQ0bnd4X014Z01XMmhJNGFvc1BBZVYwdTNqMHBXQTFqLTBNTjgyQnU3R0VmRGp5T0Z4TEFDVUMwNUVtV2pFb19STVBOUHRPN1pHbFRmNF9nWnZTZnRiOGJSbGdFcFhqWktEamV5QXhkbF9EOXhTakJDbHpJYUxqMkc5cnctV09YNzdvNG8yR09QWmVGWlc2YzYwTnJ0T1p6RVpKSk0yMmI4TWdCa081U0ZuWXh0dVY?oc=5",
          "date": "Thu, 03 Jul 2025 07:00:00 GMT",
          "category": "military conflict",
          "confidence": 0.7368147373199463,
          "weight": 7.368147373199463,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "73.7%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Bulgaria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Cabinet discusses situation in Venezuela and security risks in the region - bnrnews.bg",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNZ0U3MkhYZjlWWDZQc3hUNzZlRU9lR3R3ank4WDdkZHBSZWhIaUFrV3d4UlV4NnRRWENsVUt2QWg0VFBRaDBoTV94QUlVcmhNZ2Z4Ni1vQlJERC04NEo2OWw1UklTTl8yWHByaEluSkJPZkpfZFlGZmdtTzM2WGxudGRnVDc2RUVSeVdGMVpIWEF2MFFyM0dSRmg2QnFmd1RoNnV1d2JDVUNDXzA?oc=5",
          "date": "Mon, 12 Jan 2026 19:47:01 GMT",
          "category": "political crisis",
          "confidence": 0.6855317950248718,
          "weight": 4.113190770149231,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Moscow’s Embassy in Bulgaria Launches Fundraiser for Russian Troops",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/moscows-embassy-in-bulgaria-launches-fundraiser-for-russian-troops/",
          "date": "Mon, 27 Jun 2022 16:19:43 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.4035015404224396,
          "weight": 1.2105046212673187,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "40.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Facebook Page Uploaded Misleading Picture of Bulgarian Battalion Fighting In Ukraine",
          "translated_title": null,
          "link": "https://balkaninsight.com/techresponses/facebook-page-uploaded-misleading-picture-of-bulgarian-battalion-fighting-in-ukraine/",
          "date": "Thu, 24 Mar 2022 09:39:36 +0000",
          "category": "military conflict",
          "confidence": 0.6184794902801514,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "61.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "United States and Bulgaria Deepen Cooperation in Cybersecurity Realm - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNbW1kM0ZaZHp5VGpvZmVncWRzenNYZ3F1UjJrZGg4M3ZJczY3MFNsdHp1enoxZ0xOQmFublVQeG1UOUVmYlE5V0RCRG1wZ2VfUUpoR05sYlMyemVhY3BtN3VHeFdPb0NzZThwZUdFS1lZTTMyc3JXV2lvODNSTGswRGVEa2dhdUVtbFJrdFMzdjA3Rkc0WjNZMFNTb29EWEx5eDl4TVhnNk1GajhzREE?oc=5",
          "date": "Sat, 17 Jan 2026 07:07:30 GMT",
          "category": "violent protest",
          "confidence": 0.4376515746116638,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria - OSCE.org",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5oQXhJQVVCd3Z6ZWxpTzZ2bUZhSjNkMTJ0cURDeFZCY2p2RWxnV04xWnJ0SUVvQkZsRFI5Q3ZWSE5zcmhqMnpfV3R5T1FTZw?oc=5",
          "date": "Fri, 28 Nov 2025 15:31:15 GMT",
          "category": "neutral news",
          "confidence": 0.2624429166316986,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria - Welcome to the United Nations",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFB0OV9ZQXgwS1JkblpabXNoNExTbXlobXZ6S19UMXlmOGVSdWdkR2NlSzFBcmRfak11eFNvX0t5dTRrSXpnWlFKY1JwUlhqaFk?oc=5",
          "date": "Fri, 26 Sep 2025 07:00:00 GMT",
          "category": "neutral news",
          "confidence": 0.21918390691280365,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Von der Leyen’s plane hit by suspected Russian GPS Jamming in Bulgaria, landed Safely - Security Affairs",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi1gFBVV95cUxOc2VicmczV2ZELWxINTdVVGtlMHVmYzdodW9WbEJTZU9xMnRETlBnSzdwU01xWWROcGlQbXJsdVY0cXB4YzhXX0FhMDhBZ25kLXhyVVNiSEZWWHpiTFdhTWZ2aU10dnFqcTFiV2Z5Y2ctZkNQY2xrQjdXdG1WVjExakhxNk94YW5VYUZSWVNGVWlkekhQUHROR29wb2FQMUpqZGlWOWVoV1FDQnRhVGlVaXB6TkJLNlhwcUVIbzBQZ3loSkpfV2dDcXlOSGp1RDY3NW92VWNB?oc=5",
          "date": "Tue, 02 Sep 2025 07:00:00 GMT",
          "category": "terrorist act",
          "confidence": 0.21761685609817505,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Teledyne FLIR Defense wins $32 million contract to provide recon surveillance kit on Strykers for Bulgaria - EDR Magazine",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMizAFBVV95cUxNdmtoMmtGck5rQm1kSjBIVGxDTjlXcWdDSHktMFZUX0xYcnp6Qml2bS1zaE1COFUtci02R2pOeVFBaE1vandsckNzcEo2bDllcm45a2kyN1JjUURLU1A5V1VqRHJ1V090UzlTUHVSUHFNS1FUbV9qVDVDODdXc3VaQlRzZ280RzlWeUFySmtPeTZjdVFvNG5kUl8tUEREUExuZFU5Tk5pbUYydGJGSFhFRWRYZUZFRUpreTMyb1l0NmZCUEIxblNkTUVvWUQ?oc=5",
          "date": "Wed, 14 Jan 2026 17:45:11 GMT",
          "category": "violent protest",
          "confidence": 0.31161099672317505,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Military Representatives - Bulgaria - nato.int",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxNaUYxd1hTdVZwb3RHaUhPWHlkLUxqaGtSUjIxX002cUdUMzNGY2hrY3JZbUxYQXZFeDhmQ25pMDBuMGJPZm8zdW0wVFNQTDB6QThyYzVvM1daeEk3Y21hWExVMV93Zl8zeVY0cHFwdk1XdlVJR1F3NXE3VEF2Y2JfOWtZM3FVVFdiNjZOdVhGY0xoaGNmMW5nQWE1MUJZM05HZ1BpUVA4ZHVMZGMydW1lXy1NaDNUZw?oc=5",
          "date": "Fri, 14 Nov 2025 02:22:49 GMT",
          "category": "terrorist act",
          "confidence": 0.21724802255630493,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "How Bulgaria supplies Ukraine with weapons and ammunition - dw.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxPX3VRZ2Fkd0prZmR3RVhRbG1HNHVvTWpEbmFBZmhwWnBXSzM3M25TSWVyMnVJM3F3X2xvMHpYUEQ3TFFXS1ZQZ0llZW53bmVxMllIVjlSdnNMWTNwSHdDcl9pMTNoM3ZCd3Ezb3ItUWJWd0pGalRwbFBVcmdpY2dab0E1cGZSay1OYWV2ZkJCSmpZdml30gGUAUFVX3lxTE45aTdyT21QVWo2aloyb1p0ZnlJY2dZVmhCbmFub2lpTjlraDlEdm9WQWtlSXRUTVNwb2hnMG1ZTUs0V0J4dXJUUGFkbncyX0xLakY3eXh4Qzd6eDFHd094alFiNnZONDRaTVVFaGwteTJXcEVsZUtkU1l4N2RMOW40MTNJMEQxVGx0cHlxOXVBS196bmY?oc=5",
          "date": "Tue, 09 Sep 2025 07:00:00 GMT",
          "category": "military conflict",
          "confidence": 0.2644251883029938,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria to Equip Units With Drone Simulators, Expand Unmanned Systems - The Defense Post",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxObkJpVG5kRTR0aTNzaDVGSlFoaWh6TWFHN1ZXVEwxZ3NGUVhWNklnYUdLRWE0U010QjF4bVhVZTJMUHk3QmlOOTRCVTh2OG5fRy1MTUxVaUVnS3hsc0NqZEN5dkIwLXVuWWZKOHpaUkhHQzNwNkRXbnpCNl9wanBTUU1uVTh5UU9o0gGOAUFVX3lxTE8wS3RMdkxncFdJS3dORlZTa0dRNnlRTHFLdDFrR1dEMkVCd2pndjJxcXBTdGNnMW84d3RncHdiYUQ2RDUtVC1iVXFndWN2SzR1cnJLRkVDZTJXWkp4eDlJaTR5UVNvM01tc3pqZW9RdHVaaHJURmVuUjUwVTczQzFXc1V2ZjlkOGFURERfYXc?oc=5",
          "date": "Mon, 10 Nov 2025 08:00:00 GMT",
          "category": "military conflict",
          "confidence": 0.28879255056381226,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "🇧🇬 Bulgaria: Eurovision 2026 National Final Hosts Revealed - Eurovoix",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikAFBVV95cUxOS3pYRnY3MF8yMzdEOG9vVE5SNzV2RzgwM0JuVWN3YzN5a3pDSzFDSU5oWWwyR1BRRnZBYzhIOGgwa0oxYkFoNk15TzVDT3FzbmlyeUZqUkY4UnVBcW1iUmNsOEJMSUdHUGRobnhqNmhnVzNCelVnSjlnSFJiX241ZlBKeGZvd2tubFpFREhoNlo?oc=5",
          "date": "Sat, 17 Jan 2026 10:46:57 GMT",
          "category": "violent protest",
          "confidence": 0.3255974352359772,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "'Euro' Tops Bulgaria’s Words of 2025 - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNcGJUY1pjN3RSLWJKVS1ZYXdDRmYxOVNhbDBnS1hySzhBdGhDUTcwdk5fcllkRHAtT2ZUakhHcWxUOWljRE1EbzRjdFNnZENtLTByNS1YNzMyam85Nmo2eExDbUlaTVJhb3V0aU5kb2daSUFCVE5OX251Z3RTUFh6M2ZLalZNMzVBX0NBbkNndEVPbUE?oc=5",
          "date": "Mon, 19 Jan 2026 08:14:11 GMT",
          "category": "neutral news",
          "confidence": 0.19933144748210907,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "19.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgarian Airways seeks antitrust nod for 100% control of Silver Wings - SeeNews",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirwFBVV95cUxPU2xaS2ZuMTdJM2FORlgwa0YxbVFyOENpQlVpbGpDMkpjUk1HLWNRTGVsaFd2eGV3ZW5mNWxUM2JnbUlBejNiSTZHcE16TzNCcTFPdGVmSXg2RUhrOGkwSnZDbFNiYkNoRXZQMkJYelpiME9LQXJwVnJ1d1RlYVpTUTFITHBoOUNwT0tnc19FNEduSlgyQURaOFFoQUI3a3hmVE82TnRINVdHRmxsNnNn?oc=5",
          "date": "Mon, 19 Jan 2026 09:54:59 GMT",
          "category": "military conflict",
          "confidence": 0.2390643060207367,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    },
    "Turkey": {
      "index": 3.22,
      "raw_score": 7.3,
      "events": [
        {
          "title": "Turkey sees Syria–Kurdish forces deal as \"historic turning point\", security sources say - Reuters",
          "translated_title": "Turkey sees Syria–Kurdish forces deal as \"historic turning point\", security sources say - Reuters",
          "link": "https://news.google.com/rss/articles/CBMizwFBVV95cUxQSmNIMmxfcGtCTTNMUnR3YVFCX01xbFV2LWRTbUhaX0JWbDRRem91WFdHU0o1QTNmdWNJM0RNaGZScXJEalZvTDBDUFpjU1FTS0NUUlF4RHBOZURjVEhia3R6YjdTMExPa1d5VmpCeU81Nzk0aklLZlZRV3JhQnFYTUxua2pXNm5XZDR0a1gxX3ByUGxZLVVCQzM5WExhaDhsSWFXTTBqTmRSb2UyVGtKZFc3UEhYMG1lUWF6RUNlQ1JLRTlja00tcU1oTEhmbVU?oc=5",
          "date": "Mon, 19 Jan 2026 09:58:48 GMT",
          "category": "military conflict",
          "confidence": 0.8418036699295044,
          "weight": 8.418036699295044,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "84.2%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Turkey",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - WRAL",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimAFBVV95cUxPaHlndjJxODAyeUYwWEY3VEFEZG9QdzBnS0pKRVVqQXc4MUx4VjBkMHBZeTRGaG9qenlBN0dMMGhFbFp2OGZGOVNfMmZKSFJvaEczcFU5UkJWd0J5OE9wWDUyMFBEQ3d2M29qN09IQk02QUsySkJZMkRlSERpSTVuZnBWZmJPNEtuNlBmTko2NlEwVEtldmxHUg?oc=5",
          "date": "Sat, 17 Jan 2026 17:47:44 GMT",
          "category": "neutral news",
          "confidence": 0.4149041175842285,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Türkiye border to access internet during blackouts - Hürriyet Daily News",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipwFBVV95cUxNZk9CUTI4M0VYTU9rU1pQdjRJSTk0Mk0tQkRWb29TcW5TbklVUkUtQy1aVUl6UTc0aU9sc0NuUW5UdVVhSm1vV0tOcFoyUVFSX19TU2daN3lXcm1tX0lhN2FGaEhTcnl2cnhlQlZ0eVN1MDVFZ3hxb1FiVERXQnJvWDBfN2tVX2p0MFpQS3haaEllZVFZRTd2MWxPU1hDQkx6OUphalJoVdIBrAFBVV95cUxQS3RWZ1U2cUpMZW12OGJGYnBuS1VWcHNxb0FIcXFxcE0yR0d4dlNoV2hDZGw5clUyRjZHb0tJVUctcTQ0M2ZMT2JMYUxRR0MxcHJ6ZVNrbnNhOEJoRjlUNXVKc3cxNE9fY2g3US14Vk5NU2xyaHRnUnR4ZG9RaHNKRmNONkVfREw0bkZxSko1OVhqcUx0OUhDd0F1Ri1wd2tvY1RaMHpSaDU2OUg3?oc=5",
          "date": "Sun, 18 Jan 2026 08:06:33 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.2119559943675995,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - The Sun Chronicle",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi9AFBVV95cUxPNHM1a1drbFFVM3dSbU9FSGM4akx4ZFRDM1RVM3VSU3hzUmdxLTgyRGdTM0RNc3pqY2VSSmpfb3lHZEVfVEZ1M2N5MVhwNUZ0cVloUlBBWVZGYlNfYnZSTXc5d0JjalQwNzZhTC1CX2NITHFJS3NxemxCeURyN1Vka3hMYVFJZUgtNDhEdHFlNTZacDlBcjZyQ1pIMWhIOXJaVXp0ZzEtc3E2Vm10M2hVbU44M3VFOHUxaG9uNW1reVZKc2sweFVuN3E5am84bUtyQUwyLVRqRGIzRE85OHYxekl2NTdOSlFZWHB4T2N2eU9VS1hD?oc=5",
          "date": "Sat, 17 Jan 2026 17:41:21 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.19412647187709808,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "19.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - KRCG",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqwFBVV95cUxNa0stUVU3RGtWYXdITHhNeDZWM1loQXJXRjVfb0dYT0MySzZYX3hfV09QMW5vS2dQVnJENXlQalV5MkY3eWlwZGkzN00xWW9mVHJHQXl3Nnd1MWhpbFo2cEZmY3BFZFExcVc4akZHdnhKajRwamZMTThYcTZ5VFlMX3JTZGpZckZmUU5LNkJab09kd0RRYXJXeFRwN3VObE00Sy1CRVZ4bkpGalE?oc=5",
          "date": "Sat, 17 Jan 2026 18:18:39 GMT",
          "category": "neutral news",
          "confidence": 0.17376938462257385,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - AOL.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiigFBVV95cUxQWi1PdzFaYUtfOHlfeXFDbDI4dHpEVHgtMmduaVZwTVlWQ3NhLXJxbUJOdGVOUkxSZENmNVFyQXFsckJoZ1RpLWszeFk1M0ZHZXdVRl9Vc1pSRmswdnc3cVc0TU1ZZ0l6N0Q1aEx0UXczSnhGYkp5WVNmVDZwUkF2Ry1YdkJUQ2UyQ0E?oc=5",
          "date": "Sat, 17 Jan 2026 17:44:42 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.20162136852741241,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - Temple Daily Telegram",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilgFBVV95cUxNV0l3SnE4U2pDTkFRQmxORk5SUno0SGlybzJJdjVPeWpPNlB0bkpZWDl1RWtXMlpndy1UYXZCaHVDUGNkSUtmbnZyeUpzZy1NM0xCX19SWENYN2dXNGNSRUxVUnh5UXNmbGplZlFuUUNhRGNsWmZ0TzAwb2Q1M041YVdLeC15RWwzckJNTDVrQUhFay15emc?oc=5",
          "date": "Sat, 17 Jan 2026 17:41:21 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.17100845277309418,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Armenia legislature head declines to talk about reopening of Turkey border - Armenia News",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiTEFVX3lxTE91Wmc0b3VfSFlnN1ZZajhIU21sNXRaWUV2MzlNWEZoUmZ1TmxDdUtkcEh1WXBsN0syRkt1eGxuVV9QOXdiWmpXaFRwdzI?oc=5",
          "date": "Mon, 19 Jan 2026 10:09:00 GMT",
          "category": "neutral news",
          "confidence": 0.45878738164901733,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - The Derrick",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxOemlseWlkanR3Z25jTkNHOWxUQTJqcUpoQnJoa2VhdXZNdHI4TTZJZTJxM0hHQzNCSnhNUFljRURtTEF5bFhiZ2UtT1dqQjJ4a3VuWThGTHZBQ3l6SjEzeXhGb0pJcThhNU9XNF9KamN6LVctVGd6M1k2QkFVS0tJa2t3ZFR6YnpHcHdiUURMeWVhbEwtNXNuX3pUcndhSlhYdXNOcW9ybU9fVVBGczcwMWhva3RwLVVkTm9QeXdiZjJYWER3M3NydTJpZ05Mc1VxSWtRajdxNEpiNTFDc08yZTB3?oc=5",
          "date": "Sat, 17 Jan 2026 17:41:21 GMT",
          "category": "neutral news",
          "confidence": 0.17753422260284424,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "FCDO Issues Urgent Travel Warning for Turkey: Avoid Border Regions Due to Terrorism and Ongoing Conflict Risks - Travel And Tour World",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi7wFBVV95cUxOVjh6cm9KMHJsRFNHRC1MakltendtZlFDa0hKRkdyS01yVTZWMDdqN3dMQ3ZSclpQN0tDRHU1Q2NPazdnNUZfVzBoUmttSDN5MXFTc0lxU09fWFhwMzYtS2lpNndNMTZEZkNOWXhiWlBpVG9oQktOMExOb1Q2LWs1cUFUSXV5LUt2MFAyU0hXTU5XeHlyeDZSY3dJN1ozaGVxc29HbmZmT2h4WGczOTRselBicXlLY2tVeEdFQkpodng3ZV9BNlludzZhSjIyM20ycEJJZFVJRXhETDBNY3p5aERVbWdxbUFaY0UyMGx1OA?oc=5",
          "date": "Mon, 19 Jan 2026 07:01:52 GMT",
          "category": "terrorist act",
          "confidence": 0.1715402454137802,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - Gloucester Daily Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi_gFBVV95cUxQVEMyQkZlUTFWRjNadzJ5UGNzYWdUTWJ3aFNjTUduV2pFVE5FbFhvSXQxUjFQNEoxaDN2bjBlUy1CV1FvVzUzZURjWUZCV2ZGNlFmRmdPd2Y3YU1PLWdjRml4c0ctZEYyZDNkdm1oSGxBTW4yUFRtc0dnNW1raEM4RF9SYlhLMjd6SGpfQ3o0MnNNSHp4VXNhcXhpU0ZmMXROVjQxTHh0bUZnSlE2eEdhUmdfZXN2TS1NMTAzSERtSXJUY3pnWVlBMEZiVWdWeE9xdmw0WnZDa25vdnNaaGlEYTRleS04QTd1cTIwSHBGTlN0cm4zNTJIQXZGd0pudw?oc=5",
          "date": "Sat, 17 Jan 2026 17:41:21 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.1782887578010559,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - The Independent",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxQNDBGbUNmMFVhbFlkVVVpeVpoSGZGN19lU3ZIX1RrREJicGlIYk1UR1JtMm40SVNxNXB4U1hqTlgycVkwaGtVTHYyU0JuY1NfQnVWX01jVnpGUGQ4enczSlFkS0xEcGI4WUhmb0d4YkFoQnJVeU5LTFJDeEkxcU1Zdlhibnp4YnFN?oc=5",
          "date": "Sat, 17 Jan 2026 17:41:00 GMT",
          "category": "neutral news",
          "confidence": 0.2573035657405853,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - The Spec",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxNcFZqNGxaMnh2M29XdjRQb2VtWnY3SWQ1WjFsUklDdnBGWUw0SnVuWXgwRkJLZ3ktbmlydEdMNGROQ3FfR1NJMDA0b1BXVGNFNEp0WXZ2VlROaF9zcjVrVHgyeDYycERaTXRXOGNzZkJ1ajNaSTB2R3dlcHRXcmJNS3RpUTBwTFVmQTdGaWZuV1I3ZC1ONVVOdk42TWJmNlNtam9DN0lSa0ZBVU4tbFRoRVJCb2RlZFV0ZU9Kd0ZVNW5Xd3NDYi1VMUFEUGlGeG1QcUllTXctWkJaV2p1aXcycE50RzFtYUxTYXVSbXlVUjE?oc=5",
          "date": "Sat, 17 Jan 2026 17:42:32 GMT",
          "category": "neutral news",
          "confidence": 0.1967082917690277,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "19.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Iranians use Turkey border to access internet during blackouts - Winnipeg Free Press",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiswFBVV95cUxNNjJpSUY4bXZFNU51ek9ESmN5YUY4Yk5PcExFd2s0Tkw0WHhRZkZRRkJMcjNOVFNZOGhFN201ZEhlc1pFZjJLaW1OLVg1aXk0dVJ0Nmc3Y2pobHRycHlUMHFXTWRrVGkwWkx6cTlZNm9rU3hEdWl1TGdXN0trQmxPbDZiOEtSbndRbnhzOFBacWhGZlpTQlRLZklqcGtqYUMxVm5PSE1OeVQzc01ZbFRDVGpKTQ?oc=5",
          "date": "Sat, 17 Jan 2026 17:42:32 GMT",
          "category": "terrorist act",
          "confidence": 0.1592676341533661,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "15.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey, Qatar filling the Board of Peace void left by Israel - The Jerusalem Post",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiXEFVX3lxTE1OZkNlclVwSnZaYkhyZkk0bXhhZlBiMmc1SXNXU0MwMmNwZlFoNG1tUEl3R0FYSGdCb0tLWlowelZPdmgzckFoLU5CSm8zWGtyYi16bWw5RGtSNWRP?oc=5",
          "date": "Sun, 18 Jan 2026 19:30:29 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5579241514205933,
          "weight": -1.1158483028411865,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "55.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-01-17T11:27:00.513089",
      "main_index": 7.61,
      "index": 7.61,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T12:49:20.499578",
      "main_index": 7.92,
      "index": 7.92,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T13:48:10.320754",
      "main_index": 7.83,
      "index": 7.83,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T14:29:57.922713",
      "main_index": 7.85,
      "index": 7.85,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T15:29:15.533040",
      "main_index": 7.92,
      "index": 7.92,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T16:32:48.681193",
      "main_index": 8.13,
      "index": 8.13,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T17:28:31.181871",
      "main_index": 8.0,
      "index": 8.0,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T18:37:24.796412",
      "main_index": 7.94,
      "index": 7.94,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T19:25:25.732625",
      "main_index": 7.87,
      "index": 7.87,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T20:35:38.219626",
      "main_index": 7.64,
      "index": 7.64,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T21:28:37.387450",
      "main_index": 7.99,
      "index": 7.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T22:32:55.918275",
      "main_index": 8.05,
      "index": 8.05,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-17T23:29:46.749746",
      "main_index": 8.26,
      "index": 8.26,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T02:02:58.141749",
      "main_index": 7.9,
      "index": 7.9,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T03:57:01.315926",
      "main_index": 8.23,
      "index": 8.23,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T04:52:06.550318",
      "main_index": 8.33,
      "index": 8.33,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T05:35:19.192717",
      "main_index": 8.14,
      "index": 8.14,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T06:40:29.932838",
      "main_index": 8.2,
      "index": 8.2,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T07:28:55.690434",
      "main_index": 8.21,
      "index": 8.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T08:43:06.066233",
      "main_index": 8.21,
      "index": 8.21,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T09:32:27.967456",
      "main_index": 8.51,
      "index": 8.51,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T10:39:57.260660",
      "main_index": 8.32,
      "index": 8.32,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T11:26:47.303185",
      "main_index": 8.27,
      "index": 8.27,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T12:55:24.779749",
      "main_index": 8.4,
      "index": 8.4,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T13:40:02.386928",
      "main_index": 8.4,
      "index": 8.4,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T14:29:26.942427",
      "main_index": 8.54,
      "index": 8.54,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T15:29:11.569699",
      "main_index": 8.43,
      "index": 8.43,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T16:38:53.328675",
      "main_index": 8.36,
      "index": 8.36,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T17:28:37.609231",
      "main_index": 8.32,
      "index": 8.32,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T18:37:02.033541",
      "main_index": 8.28,
      "index": 8.28,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T19:32:23.445636",
      "main_index": 8.15,
      "index": 8.15,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T20:38:14.064006",
      "main_index": 7.95,
      "index": 7.95,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T21:27:49.864442",
      "main_index": 7.86,
      "index": 7.86,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T22:30:28.438730",
      "main_index": 8.08,
      "index": 8.08,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-18T23:30:01.871228",
      "main_index": 8.15,
      "index": 8.15,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T01:54:56.724173",
      "main_index": 8.31,
      "index": 8.31,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T04:01:15.814929",
      "main_index": 7.96,
      "index": 7.96,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T05:03:12.544471",
      "main_index": 7.99,
      "index": 7.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T05:41:17.538191",
      "main_index": 7.98,
      "index": 7.98,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T06:55:00.264077",
      "main_index": 7.9,
      "index": 7.9,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T07:39:49.127700",
      "main_index": 7.95,
      "index": 7.95,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T08:41:46.171288",
      "main_index": 7.99,
      "index": 7.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T09:45:35.100734",
      "main_index": 8.02,
      "index": 8.02,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-19T10:38:45.843875",
      "main_index": 8.11,
      "index": 8.11,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-01-19T11:38:45.843875",
      "index": 7.89,
      "main_index": 7.89,
      "confidence": 0.56,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-19T12:38:45.843875",
      "index": 7.87,
      "main_index": 7.87,
      "confidence": 0.51,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-19T13:38:45.843875",
      "index": 7.84,
      "main_index": 7.84,
      "confidence": 0.46,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-19T14:38:45.843875",
      "index": 7.82,
      "main_index": 7.82,
      "confidence": 0.41,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-19T15:38:45.843875",
      "index": 7.8,
      "main_index": 7.8,
      "confidence": 0.36,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-19T16:38:45.843875",
      "index": 7.78,
      "main_index": 7.78,
      "confidence": 0.32,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "Modified Goldstein Scale",
    "description": "AI-powered threat classification using XLM-RoBERTa multilingual model with category-weighted scoring",
    "weights": {
      "military conflict": 10.0,
      "terrorist act": 9.0,
      "violent protest": 7.0,
      "political crisis": 6.0,
      "economic crisis": 4.0,
      "humanitarian crisis": 3.0,
      "peaceful diplomacy": -2.0,
      "neutral news": 0.0
    },
    "formula": "ThreatIndex = log10(1 + sum(category_weight * confidence)) * 3.5",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  }
};