window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-01-16T21:25:31.320874",
    "main_index": 7.36,
    "status": "CRITICAL",
    "active_scan": true,
    "next_update": "2026-01-16T22:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 3.02,
      "raw_score": 6.3,
      "events": [
        {
          "title": "ANCA calls for expanded U.S. efforts to end Azerbaijan’s hostage diplomacy",
          "translated_title": "ANCA calls for expanded U.S. efforts to end Azerbaijan’s hostage diplomacy",
          "link": "https://armenianweekly.com/2026/01/14/anca-calls-for-expanded-u-s-efforts-to-end-azerbaijans-hostage-diplomacy/",
          "date": "Thu, 15 Jan 2026 00:11:57 +0000",
          "category": "political crisis",
          "confidence": 0.9169823527336121,
          "weight": 5.501894116401672,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "91.7%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Armenia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Jammed Capital: How to Manage the Chaos",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179262",
          "date": "Fri, 16 Jan 2026 11:38:00 +0400",
          "category": "economic crisis",
          "confidence": 0.6424645781517029,
          "weight": 2.5698583126068115,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "64.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Sovereignty or strategy? U.S. to take majority stake in company managing TRIPP corridor",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/16/sovereignty-or-strategy-u-s-to-take-majority-stake-in-company-managing-tripp-corridor/",
          "date": "Fri, 16 Jan 2026 18:47:05 +0000",
          "category": "military conflict",
          "confidence": 0.22157469391822815,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The Region in Brief",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/15/the-region-in-brief-153/",
          "date": "Thu, 15 Jan 2026 19:52:18 +0000",
          "category": "violent protest",
          "confidence": 0.16657644510269165,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "16.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Birds as messengers from Heaven",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/15/birds-as-messengers-from-heaven/",
          "date": "Thu, 15 Jan 2026 19:18:06 +0000",
          "category": "terrorist act",
          "confidence": 0.20082761347293854,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "20.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The Armenian community in São Paulo, Brazil: Reviving youth through sports, culture and heritage",
          "translated_title": null,
          "link": "https://armenianweekly.com/2026/01/15/the-armenian-community-in-sao-paulo-brazil-reviving-youth-through-sports-culture-and-heritage/",
          "date": "Thu, 15 Jan 2026 18:40:46 +0000",
          "category": "neutral news",
          "confidence": 0.2982791066169739,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Ucom Introduces Hecttor AI to Improve Call Center Communications",
          "translated_title": null,
          "link": "https://a1plus.am/en/article/496401",
          "date": "Tue, 13 Jan 2026 13:51:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.17270758748054504,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Khachkar Studios Publishes New Systems Map of a Failing U.S. Armenian Christian Ecosystem",
          "translated_title": null,
          "link": "https://a1plus.am/en/article/496126",
          "date": "Tue, 06 Jan 2026 00:25:00 +0400",
          "category": "economic crisis",
          "confidence": 0.17597264051437378,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Switzerland takes over OSCE Chair",
          "translated_title": null,
          "link": "https://a1plus.am/en/article/496020",
          "date": "Thu, 01 Jan 2026 12:05:00 +0400",
          "category": "neutral news",
          "confidence": 0.23620426654815674,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "New Year’s Message of His Holiness Karekin II, Supreme Patriarch and Catholicos of All Armenians (video)",
          "translated_title": null,
          "link": "https://a1plus.am/en/article/496011",
          "date": "Wed, 31 Dec 2025 23:38:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.23078210651874542,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "The FINTECH360 conference will be held in Yerevan from April 27 to 29",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179277",
          "date": "Fri, 16 Jan 2026 23:39:00 +0400",
          "category": "neutral news",
          "confidence": 0.28947266936302185,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Businessman Samvel Karapetyan Sent Back to Jail",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179267",
          "date": "Fri, 16 Jan 2026 14:46:00 +0400",
          "category": "neutral news",
          "confidence": 0.214456245303154,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "From Artsakh to London: A Stretched Guitar String",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179135",
          "date": "Fri, 16 Jan 2026 11:31:00 +0400",
          "category": "violent protest",
          "confidence": 0.27046987414360046,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Hayk Isakhanyan: Refitting a Soviet Knitwear Factory to Produce Wine Barrels",
          "translated_title": null,
          "link": "https://hetq.am/en/article/179251",
          "date": "Thu, 15 Jan 2026 19:00:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.2518221437931061,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Joint Statement on the Publication of the Armenia-U.S. Implementation Framework for the Trump Route for International Peace and Prosperity (TRIPP)",
          "translated_title": null,
          "link": "https://a1plus.am/en/article/496436",
          "date": "Wed, 14 Jan 2026 10:05:00 +0400",
          "category": "peaceful diplomacy",
          "confidence": 0.8854080438613892,
          "weight": -1.7708160877227783,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "88.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 5.01,
      "raw_score": 26.06,
      "events": [
        {
          "title": "Georgian Dream files complaint with BBC over allegations WWI-era chemical was used on protesters",
          "translated_title": "Georgian Dream files complaint with BBC over allegations WWI-era chemical was used on protesters",
          "link": "https://oc-media.org/georgian-dream-files-complaint-with-bbc-over-allegations-wwi-era-chemical-was-used-on-protesters/",
          "date": "Fri, 16 Jan 2026 14:38:47 +0000",
          "category": "military conflict",
          "confidence": 0.9743887186050415,
          "weight": 9.743887186050415,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgian intelligence probes appearance of Gazprom documents on government website as ‘cyberattack’",
          "translated_title": "Georgian intelligence probes appearance of Gazprom documents on government website as ‘cyberattack’",
          "link": "https://oc-media.org/georgian-intelligence-probes-appearance-of-gazprom-documents-on-government-website-as-cyberattack/",
          "date": "Fri, 16 Jan 2026 15:41:24 +0000",
          "category": "terrorist act",
          "confidence": 0.9081418514251709,
          "weight": 8.173276662826538,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "90.8%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Ingush woman who fled domestic violence detained in Moscow",
          "translated_title": "Ingush woman who fled domestic violence detained in Moscow",
          "link": "https://oc-media.org/ingush-woman-who-fled-domestic-violence-detained-in-moscow/",
          "date": "Thu, 15 Jan 2026 12:11:37 +0000",
          "category": "violent protest",
          "confidence": 0.6804161071777344,
          "weight": 4.762912750244141,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "68.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "What would an Iranian revolution mean for the Caucasus?",
          "translated_title": "What would an Iranian revolution mean for the Caucasus?",
          "link": "https://oc-media.org/what-would-an-iranian-revolution-mean-for-the-caucasus/",
          "date": "Thu, 15 Jan 2026 13:36:42 +0000",
          "category": "political crisis",
          "confidence": 0.7341688871383667,
          "weight": 4.4050133228302,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "73.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Breaking: Kadyrov’s son Adam reportedly in critical condition after car accident",
          "translated_title": null,
          "link": "https://oc-media.org/breaking-kadyrovs-son-adam-reportedly-in-critical-condition-after-car-accident/",
          "date": "Fri, 16 Jan 2026 18:38:21 +0000",
          "category": "violent protest",
          "confidence": 0.37145474553108215,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "37.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Armenians and Georgians number among killed in Iran protests, reports say",
          "translated_title": null,
          "link": "https://oc-media.org/armenians-and-georgians-number-among-killed-in-iran-protests-reports-say/",
          "date": "Fri, 16 Jan 2026 14:21:15 +0000",
          "category": "violent protest",
          "confidence": 0.3849703073501587,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Solovyov’s suggestion of ‘special military operation’ in Armenia a ‘personal opinion’, Kremlin says",
          "translated_title": null,
          "link": "https://oc-media.org/solovyovs-suggestion-of-special-military-operation-in-armenia-a-personal-opinion-kremlin-says/",
          "date": "Fri, 16 Jan 2026 14:11:51 +0000",
          "category": "military conflict",
          "confidence": 0.3002075254917145,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "‘Help must reach the people of Iran’ — Iranians demonstrate in Tbilisi and Yerevan",
          "translated_title": null,
          "link": "https://oc-media.org/help-must-reach-the-people-of-iran-iranians-demonstrate-in-tbilisi-and-yerevan/",
          "date": "Fri, 16 Jan 2026 14:04:45 +0000",
          "category": "violent protest",
          "confidence": 0.23250791430473328,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Army chaplains reportedly pressured to join Pashinyan’s Church reform initiative",
          "translated_title": null,
          "link": "https://oc-media.org/army-chaplains-reportedly-pressured-to-join-pashinyans-church-reform-initiative/",
          "date": "Fri, 16 Jan 2026 13:57:08 +0000",
          "category": "political crisis",
          "confidence": 0.32414892315864563,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Azerbaijan’s anti-colonialist Baku Initiative Group turns its focus on India’s treatment of Sikhs",
          "translated_title": null,
          "link": "https://oc-media.org/azerbaijans-anti-colonialist-baku-initiative-group-turns-its-focus-on-indias-treatment-of-sikhs/",
          "date": "Fri, 16 Jan 2026 13:02:55 +0000",
          "category": "political crisis",
          "confidence": 0.2926677465438843,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Chechen Parliament approves appointment of Kadyrov’s son as deputy prime minister",
          "translated_title": null,
          "link": "https://oc-media.org/chechen-parliament-approves-appointment-of-kadyrovs-son-as-deputy-prime-minister/",
          "date": "Fri, 16 Jan 2026 11:56:28 +0000",
          "category": "political crisis",
          "confidence": 0.23483343422412872,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Azerbaijan’s SOCAR to begin supplying gas to Austria and Germany",
          "translated_title": null,
          "link": "https://oc-media.org/azerbaijans-socar-to-begin-supplying-gas-to-austria-and-germany/",
          "date": "Fri, 16 Jan 2026 11:10:16 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.23145128786563873,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "What can the Caucasus expect in 2026? Our staff gives their takes",
          "translated_title": null,
          "link": "https://oc-media.org/what-can-the-caucasus-expect-in-2026-our-staff-give-their-takes/",
          "date": "Fri, 16 Jan 2026 09:55:32 +0000",
          "category": "terrorist act",
          "confidence": 0.2197570502758026,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Friday, 16 January 2025",
          "translated_title": null,
          "link": "https://oc-media.org/friday-16-january-2025/",
          "date": "Fri, 16 Jan 2026 09:21:57 +0000",
          "category": "neutral news",
          "confidence": 0.23797442018985748,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Ingush Head Kalimatov claims authorities settled 6 blood feuds and 40 conflicts",
          "translated_title": null,
          "link": "https://oc-media.org/ingush-head-kalimatov-claims-authorities-settled-6-blood-feuds-and-40-conflicts/",
          "date": "Thu, 15 Jan 2026 14:31:34 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.512917697429657,
          "weight": -1.025835394859314,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "51.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 2.41,
      "raw_score": 3.87,
      "events": [
        {
          "title": "Φενέρμπαχτσε - Βαλένθια: 82-79: Σαν να μην πέρασε μια μέρα για Φενέρ και Ντε Κολό!",
          "translated_title": "Fenerbahce - Valencia: 82-79: As if not a day has passed for Fener and De Colo!",
          "link": "https://www.protothema.gr/sports/article/1758873/fenerbahtse-valenthia-82-79-san-na-min-perase-mia-mera-gia-fener-kai-de-kolo/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:52:00 +0200",
          "category": "violent protest",
          "confidence": 0.6230836510658264,
          "weight": 4.361585557460785,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "62.3%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Greece",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Wall Street: Μικρές διακυμάνσεις και ήπιες απώλειες μετά τις δηλώσεις Τραμπ για την Fed",
          "translated_title": null,
          "link": "https://www.protothema.gr/economy/article/1758887/wall-street-mikres-diakumanseis-kai-ipies-apoleies-meta-tis-diloseis-trab-gia-tin-fed/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 23:12:04 +0200",
          "category": "political crisis",
          "confidence": 0.507466733455658,
          "weight": 3.0448004007339478,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "50.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Άνοιγμα του Αλ Σάρα στην κουρδική μειονότητα της Συρίας: Χορηγεί δικαιώματα, αναγνωρίζει ως επίσημη γλώσσα τα κουρδικά",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1758883/anoigma-tou-al-sara-stin-kourdiki-meionotita-tis-surias-horigei-dikaiomata-anagnorizei-os-episimi-glossa-ta-kourdika/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 23:04:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.21406742930412292,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Νεκρός ο 18χρονος μαθητής που μαχαιρώθηκε μέσα σε σχολείο της Ιταλίας",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1758881/nekros-o-18hronos-mathitis-pou-mahairothike-mesa-se-sholeio-tis-italias/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:59:28 +0200",
          "category": "terrorist act",
          "confidence": 0.28166595101356506,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Συγκέντρωση έξω από την πρεσβεία του Ιράν στο Ψυχικό, δείτε βίντεο και φωτογραφίες",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1758870/sugedrosi-exo-apo-tin-presveia-tou-iran-sto-psuhiko-deite-video-kai-fotografies/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:44:14 +0200",
          "category": "neutral news",
          "confidence": 0.18554337322711945,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Το Νόμπελ είναι «δεμένο» με τον βραβευμένο, υπενθυμίζει ξανά η επιτροπή απονομής στη Ματσάδο",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1758869/to-nobel-einai-demeno-me-ton-vraveumeno-upenthumizei-xana-i-epitropi-aponomis-sti-matsado/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:43:00 +0200",
          "category": "violent protest",
          "confidence": 0.22298522293567657,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Η Πάμελα Άντερσον εξομολογήθηκε ότι ένιωσε αηδία που βρέθηκε κοντά στον Σεθ Ρόγκεν στις Χρυσές Σφαίρες",
          "translated_title": null,
          "link": "https://www.protothema.gr/life-style/article/1758867/i-pamela-aderson-exomologithike-oti-eniose-aidia-otan-vrethike-koda-ston-seth-rogen-stis-hruses-sfaires/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:35:00 +0200",
          "category": "violent protest",
          "confidence": 0.3846939206123352,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Παναθηναϊκός: Την Κυριακή στην Αθήνα ο Αντίνο",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1758860/panathinaikos-tin-kuriaki-stin-athina-o-adino/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:32:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.17588728666305542,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "«Είχαν πάθει σοκ και οι αστυνομικοί»: Η μαρτυρία της υπαλλήλου που αποκάλυψε την hi tech απάτη των Κινέζων που πιάστηκαν στα Σπάτα",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1758857/eihan-pathei-sok-astunomikoi-marturia-tis-upallilou-pou-apokalupse-tin-hi-tech-apati-ton-kinezon-pou-piastikan-sta-spata/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:31:29 +0200",
          "category": "terrorist act",
          "confidence": 0.3087410032749176,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Συνάντηση Ουκρανών και Αμερικανών διαπραγματευτών αύριο στο Μαϊάμι",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1758854/sunadisi-oukranon-kai-amerikanon-diapragmateuton-aurio-sto-maiami/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:26:00 +0200",
          "category": "terrorist act",
          "confidence": 0.2655639350414276,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Γιώργος Ζυγούρης για «Σέρρες»: Στην αρχή ο Γιώργος Καπουτζίδης δεν ήταν καθόλου σίγουρος για μένα",
          "translated_title": null,
          "link": "https://www.protothema.gr/life-style/article/1758853/giorgos-zugouris-gia-tis-serres-stin-arhi-o-giorgos-kapoutzidis-den-itan-katholou-sigouros-gia-mena/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:05:00 +0200",
          "category": "violent protest",
          "confidence": 0.21889880299568176,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ο Φαν Νίστελροϊ στο τεχνικό επιτελείο της Εθνικής Ολλανδίας",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1758848/o-fan-nistelroi-sto-tehniko-epiteleio-tis-ethnikis-ollandias/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:16:00 +0200",
          "category": "neutral news",
          "confidence": 0.2471092939376831,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Συνελήφθη οδηγός που έτρεχε με 191 χιλιόμετρα την ώρα στην Περιφερειακή Υμηττού",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1758847/sunelifthi-allodapos-odigos-pou-etrehe-me-191-hiliometra-tin-ora-stin-perifereiaki-umittou/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 21:56:00 +0200",
          "category": "violent protest",
          "confidence": 0.21339842677116394,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Κλήρωση Eurojackpot 16/1/2025: Τα αποτελέσματα και οι αριθμοί που κερδίζουν",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1758846/klirosi-eurojackpot-1612025-ta-apotelesmata-kai-oi-arithmoi-pou-kerdizoun/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 21:55:00 +0200",
          "category": "violent protest",
          "confidence": 0.33061283826828003,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ράντου και Παπακωνσταντίνου: Έξοδος για το ζευγάρι στο μαγαζί που εμφανίζονται η Παπαρίζου και ο Ζαχαράτος",
          "translated_title": null,
          "link": "https://www.protothema.gr/life-style/article/1758878/radou-kai-papakonstadinou-exodos-gia-to-zeugari-sto-magazi-pou-emfanizodai-i-paparizou-kai-o-zaharatos/?utm_source=rss",
          "date": "Fri, 16 Jan 2026 22:57:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.4802301824092865,
          "weight": -0.960460364818573,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "48.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    },
    "Iraq": {
      "index": 5.67,
      "raw_score": 40.62,
      "events": [
        {
          "title": "Saudi–Egypt–Somalia military bloc 'taking shape' amid tensions",
          "translated_title": "Saudi–Egypt–Somalia military bloc 'taking shape' amid tensions",
          "link": "https://www.newarab.com/news/saudi-egypt-somalia-military-bloc-taking-shape-amid-tensions",
          "date": "Fri, 16 Jan 2026 16:42:16 +0000",
          "category": "military conflict",
          "confidence": 0.8948183059692383,
          "weight": 8.948183059692383,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "89.5%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Iraq",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Chad says seven soldiers killed in clash at Sudanese border",
          "translated_title": "Chad says seven soldiers killed in clash at Sudanese border",
          "link": "https://www.newarab.com/news/chad-says-seven-soldiers-killed-clash-sudanese-border",
          "date": "Fri, 16 Jan 2026 20:45:29 +0000",
          "category": "military conflict",
          "confidence": 0.8649976253509521,
          "weight": 8.649976253509521,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "86.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "US threatens funding freeze over Palestine UN bid and ICC action",
          "translated_title": "US threatens funding freeze over Palestine UN bid and ICC action",
          "link": "https://www.newarab.com/news/us-threatens-funding-freeze-over-palestine-un-bid-and-icc-action",
          "date": "Fri, 16 Jan 2026 17:52:15 +0000",
          "category": "political crisis",
          "confidence": 0.9439144134521484,
          "weight": 5.663486480712891,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "94.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Local UK police chief retires amid Maccabi fan ban row",
          "translated_title": "Local UK police chief retires amid Maccabi fan ban row",
          "link": "https://www.newarab.com/news/local-uk-police-chief-retires-amid-maccabi-fan-ban-row",
          "date": "Fri, 16 Jan 2026 19:44:19 +0000",
          "category": "political crisis",
          "confidence": 0.70353102684021,
          "weight": 4.22118616104126,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "70.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Yemen prosecutor seeking to investigate STC head for 'treason'",
          "translated_title": null,
          "link": "https://www.newarab.com/news/yemen-prosecutor-seeking-investigate-stc-head-treason",
          "date": "Fri, 16 Jan 2026 17:30:23 +0000",
          "category": "political crisis",
          "confidence": 0.6088765859603882,
          "weight": 3.653259515762329,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "60.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Lebanon detains Syrian who helped fund pro-Assad fighters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/lebanon-detains-syrian-who-helped-fund-pro-assad-fighters",
          "date": "Fri, 16 Jan 2026 16:22:27 +0000",
          "category": "political crisis",
          "confidence": 0.5723428726196289,
          "weight": 3.4340572357177734,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "57.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Kurdish group claims armed actions in Iran to defend protesters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/kurdish-group-claims-armed-actions-iran-defend-protesters",
          "date": "Fri, 16 Jan 2026 17:14:01 +0000",
          "category": "political crisis",
          "confidence": 0.5383753776550293,
          "weight": 3.230252265930176,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "53.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Gaza economy pins hopes on implementing ceasefire phase two",
          "translated_title": null,
          "link": "https://www.newarab.com/news/gaza-economy-pins-hopes-implementing-ceasefire-phase-two",
          "date": "Fri, 16 Jan 2026 16:39:46 +0000",
          "category": "economic crisis",
          "confidence": 0.704861044883728,
          "weight": 2.819444179534912,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "70.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "IShowSpeed goes viral for 'first ever' Egypt pyramids livestream",
          "translated_title": null,
          "link": "https://www.newarab.com/news/ishowspeed-goes-viral-first-ever-egypt-pyramids-livestream",
          "date": "Fri, 16 Jan 2026 18:19:52 +0000",
          "category": "violent protest",
          "confidence": 0.238638237118721,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Israel bars PA Jerusalem affairs minister from West Bank",
          "translated_title": null,
          "link": "https://www.newarab.com/news/israel-bars-pa-jerusalem-affairs-minister-west-bank",
          "date": "Fri, 16 Jan 2026 17:59:14 +0000",
          "category": "political crisis",
          "confidence": 0.17980007827281952,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Saudi Arabia's King Salman undergoes medical tests: royal court",
          "translated_title": null,
          "link": "https://www.newarab.com/news/saudi-arabias-king-salman-undergoes-medical-tests-royal-court",
          "date": "Fri, 16 Jan 2026 17:57:26 +0000",
          "category": "violent protest",
          "confidence": 0.41218098998069763,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "US congress members visit Denmark to support Greenland",
          "translated_title": null,
          "link": "https://www.newarab.com/news/us-congress-members-visit-denmark-support-greenland",
          "date": "Fri, 16 Jan 2026 17:40:55 +0000",
          "category": "neutral news",
          "confidence": 0.38671940565109253,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Exclusive: Hamas says US must oblige Israel to move to phase two",
          "translated_title": null,
          "link": "https://www.newarab.com/news/exclusive-hamas-says-us-must-oblige-israel-move-phase-two",
          "date": "Fri, 16 Jan 2026 16:48:16 +0000",
          "category": "political crisis",
          "confidence": 0.26448723673820496,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Kuwait revokes citizenship of its serving ambassador to London",
          "translated_title": null,
          "link": "https://www.newarab.com/news/kuwait-revokes-citizenship-its-serving-ambassador-london",
          "date": "Fri, 16 Jan 2026 16:19:46 +0000",
          "category": "violent protest",
          "confidence": 0.18401268124580383,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Donald Trump, Viceroy of Gaza",
          "translated_title": null,
          "link": "https://www.newarab.com/graphic-truth/donald-trump-viceroy-gaza",
          "date": "Fri, 16 Jan 2026 16:08:54 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.3708983361721039,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "37.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 5.67,
      "raw_score": 40.62,
      "events": [
        {
          "title": "Saudi–Egypt–Somalia military bloc 'taking shape' amid tensions",
          "translated_title": "Saudi–Egypt–Somalia military bloc 'taking shape' amid tensions",
          "link": "https://www.newarab.com/news/saudi-egypt-somalia-military-bloc-taking-shape-amid-tensions",
          "date": "Fri, 16 Jan 2026 16:42:16 +0000",
          "category": "military conflict",
          "confidence": 0.8948183059692383,
          "weight": 8.948183059692383,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "89.5%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Chad says seven soldiers killed in clash at Sudanese border",
          "translated_title": "Chad says seven soldiers killed in clash at Sudanese border",
          "link": "https://www.newarab.com/news/chad-says-seven-soldiers-killed-clash-sudanese-border",
          "date": "Fri, 16 Jan 2026 20:45:29 +0000",
          "category": "military conflict",
          "confidence": 0.8649976253509521,
          "weight": 8.649976253509521,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "86.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "US threatens funding freeze over Palestine UN bid and ICC action",
          "translated_title": "US threatens funding freeze over Palestine UN bid and ICC action",
          "link": "https://www.newarab.com/news/us-threatens-funding-freeze-over-palestine-un-bid-and-icc-action",
          "date": "Fri, 16 Jan 2026 17:52:15 +0000",
          "category": "political crisis",
          "confidence": 0.9439144134521484,
          "weight": 5.663486480712891,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "94.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Local UK police chief retires amid Maccabi fan ban row",
          "translated_title": "Local UK police chief retires amid Maccabi fan ban row",
          "link": "https://www.newarab.com/news/local-uk-police-chief-retires-amid-maccabi-fan-ban-row",
          "date": "Fri, 16 Jan 2026 19:44:19 +0000",
          "category": "political crisis",
          "confidence": 0.70353102684021,
          "weight": 4.22118616104126,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "70.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Yemen prosecutor seeking to investigate STC head for 'treason'",
          "translated_title": null,
          "link": "https://www.newarab.com/news/yemen-prosecutor-seeking-investigate-stc-head-treason",
          "date": "Fri, 16 Jan 2026 17:30:23 +0000",
          "category": "political crisis",
          "confidence": 0.6088765859603882,
          "weight": 3.653259515762329,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "60.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Lebanon detains Syrian who helped fund pro-Assad fighters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/lebanon-detains-syrian-who-helped-fund-pro-assad-fighters",
          "date": "Fri, 16 Jan 2026 16:22:27 +0000",
          "category": "political crisis",
          "confidence": 0.5723428726196289,
          "weight": 3.4340572357177734,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "57.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Kurdish group claims armed actions in Iran to defend protesters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/kurdish-group-claims-armed-actions-iran-defend-protesters",
          "date": "Fri, 16 Jan 2026 17:14:01 +0000",
          "category": "political crisis",
          "confidence": 0.5383753776550293,
          "weight": 3.230252265930176,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "53.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Gaza economy pins hopes on implementing ceasefire phase two",
          "translated_title": null,
          "link": "https://www.newarab.com/news/gaza-economy-pins-hopes-implementing-ceasefire-phase-two",
          "date": "Fri, 16 Jan 2026 16:39:46 +0000",
          "category": "economic crisis",
          "confidence": 0.704861044883728,
          "weight": 2.819444179534912,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "70.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "IShowSpeed goes viral for 'first ever' Egypt pyramids livestream",
          "translated_title": null,
          "link": "https://www.newarab.com/news/ishowspeed-goes-viral-first-ever-egypt-pyramids-livestream",
          "date": "Fri, 16 Jan 2026 18:19:52 +0000",
          "category": "violent protest",
          "confidence": 0.238638237118721,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Israel bars PA Jerusalem affairs minister from West Bank",
          "translated_title": null,
          "link": "https://www.newarab.com/news/israel-bars-pa-jerusalem-affairs-minister-west-bank",
          "date": "Fri, 16 Jan 2026 17:59:14 +0000",
          "category": "political crisis",
          "confidence": 0.17980007827281952,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Saudi Arabia's King Salman undergoes medical tests: royal court",
          "translated_title": null,
          "link": "https://www.newarab.com/news/saudi-arabias-king-salman-undergoes-medical-tests-royal-court",
          "date": "Fri, 16 Jan 2026 17:57:26 +0000",
          "category": "violent protest",
          "confidence": 0.41218098998069763,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "US congress members visit Denmark to support Greenland",
          "translated_title": null,
          "link": "https://www.newarab.com/news/us-congress-members-visit-denmark-support-greenland",
          "date": "Fri, 16 Jan 2026 17:40:55 +0000",
          "category": "neutral news",
          "confidence": 0.38671940565109253,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Exclusive: Hamas says US must oblige Israel to move to phase two",
          "translated_title": null,
          "link": "https://www.newarab.com/news/exclusive-hamas-says-us-must-oblige-israel-move-phase-two",
          "date": "Fri, 16 Jan 2026 16:48:16 +0000",
          "category": "political crisis",
          "confidence": 0.26448723673820496,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Kuwait revokes citizenship of its serving ambassador to London",
          "translated_title": null,
          "link": "https://www.newarab.com/news/kuwait-revokes-citizenship-its-serving-ambassador-london",
          "date": "Fri, 16 Jan 2026 16:19:46 +0000",
          "category": "violent protest",
          "confidence": 0.18401268124580383,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Donald Trump, Viceroy of Gaza",
          "translated_title": null,
          "link": "https://www.newarab.com/graphic-truth/donald-trump-viceroy-gaza",
          "date": "Fri, 16 Jan 2026 16:08:54 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.3708983361721039,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "37.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 3.44,
      "raw_score": 8.61,
      "events": [
        {
          "title": "Синът на последния ирански шах поиска засилен международен натиск срещу режима",
          "translated_title": "The son of Iran's last shah called for increased international pressure against the regime",
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873726_sinut_na_posledniia_iranski_shah_poiska_zasilen/?ref=rss",
          "date": "Fri, 16 Jan 2026 21:27:00 +0200",
          "category": "political crisis",
          "confidence": 0.8906182646751404,
          "weight": 5.343709588050842,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "89.1%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Bulgaria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Петър Ганев: Въвеждането на еврото вървеше добре, докато депутатите не се върнаха на работа",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/biznes/2026/01/16/4873728_petur_ganev_vuvejdaneto_na_evroto_vurveshe_dobre/?ref=rss",
          "date": "Fri, 16 Jan 2026 21:20:00 +0200",
          "category": "political crisis",
          "confidence": 0.5440384745597839,
          "weight": 3.2642308473587036,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "54.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Шараа обяви кюрдския език за национален в Сирия",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873753_sharaa_obiavi_kjurdskiia_ezik_za_nacionalen_v_siriia/?ref=rss",
          "date": "Fri, 16 Jan 2026 22:55:00 +0200",
          "category": "neutral news",
          "confidence": 0.3051168620586395,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Мачадо омаловажи Родригес като президент на Венецуела, САЩ са на друго мнение",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873734_machado_omalovaji_rodriges_kato_prezident_na_venecuela/?ref=rss",
          "date": "Fri, 16 Jan 2026 22:10:00 +0200",
          "category": "political crisis",
          "confidence": 0.44065380096435547,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "44.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Киев разполага само с половината от необходимия ток, каза Кличко",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/voinata_v_ukraina/2026/01/16/4873722_kiev_razpolaga_samo_s_polovinata_ot_neobhodimiia_tok/?ref=rss",
          "date": "Fri, 16 Jan 2026 20:59:00 +0200",
          "category": "neutral news",
          "confidence": 0.25128066539764404,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Близо 60% от левовете в обращение вече са изтеглени",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/biznes/2026/01/16/4873717_blizo_60_ot_levovete_v_obrashtenie_veche_sa_izvadeni/?ref=rss",
          "date": "Fri, 16 Jan 2026 20:35:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.31224948167800903,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Пет са подадените оферти за ремонта на тунел на \"Тракия\" за над 40 млн. евро",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/01/16/4873658_petima_sa_kandidatite_za_remonta_na_tunel_na_trakiia/?ref=rss",
          "date": "Fri, 16 Jan 2026 19:42:00 +0200",
          "category": "military conflict",
          "confidence": 0.25825008749961853,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Китайските университети се изкачват в глобалните класации, американските губят позиции",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/obrazovanie/2026/01/16/4873711_kitaiskite_universiteti_se_izkachvat_v_globalnite/?ref=rss",
          "date": "Fri, 16 Jan 2026 19:33:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.2464282363653183,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Съдът в Смолян пусна под гаранция от 5000 лв. Божидар Бобоков",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/01/16/4873712_sudut_v_smolian_pusna_pod_garanciia_ot_5000_lv_bojidar/?ref=rss",
          "date": "Fri, 16 Jan 2026 19:25:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.18350128829479218,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Кметът Васил Терзиев отново предлага анализ от Световната банка за \"Топлофикация София\"",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/gradska_sreda/2026/01/16/4873695_kmetut_vasil_terziev_otnovo_predlaga_analiz_ot/?ref=rss",
          "date": "Fri, 16 Jan 2026 18:42:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.16229845583438873,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "16.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Тръмп заплаши с мита държавите, които не приемат да получи Гренландия",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873694_trump_zaplashi_s_mita_durjavite_koito_ne_priemat_da/?ref=rss",
          "date": "Fri, 16 Jan 2026 18:34:00 +0200",
          "category": "violent protest",
          "confidence": 0.17476096749305725,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Отказаните молби за визи за САЩ са паднали до около 5%",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/01/16/4873663_otkazanite_molbi_za_vizi_za_sasht_sa_padnali_do_okolo_5/?ref=rss",
          "date": "Fri, 16 Jan 2026 18:15:00 +0200",
          "category": "neutral news",
          "confidence": 0.32575690746307373,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Москва започна съдебен процес срещу \"Юроклиър\"",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873677_moskva_zapochna_sudeben_proces_sreshtu_jurokliur/?ref=rss",
          "date": "Fri, 16 Jan 2026 18:06:00 +0200",
          "category": "military conflict",
          "confidence": 0.4639565646648407,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "46.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Двама въоръжени мъже обраха инкасо автомобил в Ихтиман",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/bulgaria/2026/01/16/4873665_kradci_obraha_inkaso_avtomobil_v_ihtiman/?ref=rss",
          "date": "Fri, 16 Jan 2026 17:34:00 +0200",
          "category": "violent protest",
          "confidence": 0.31844618916511536,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Съветник в Белия дом не очаква изненади от разследването срещу Пауъл",
          "translated_title": null,
          "link": "https://www.dnevnik.bg/sviat/2026/01/16/4873659_suvetnik_v_beliia_dom_ne_ochakva_iznenadi_ot/?ref=rss",
          "date": "Fri, 16 Jan 2026 17:18:00 +0200",
          "category": "neutral news",
          "confidence": 0.2555067539215088,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    },
    "Turkey": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": []
    }
  },
  "history": [
    {
      "timestamp": "2026-01-01T20:06:49.349310",
      "index": 7.46,
      "main_index": NaN,
      "georgia_idx": 0.0,
      "georgia_signals": 0,
      "syria_signals": 0,
      "greece_signals": 0,
      "syria_idx": 0.0,
      "total_signals": 0,
      "greece_idx": 0.0,
      "armenia_idx": 0.0,
      "iran_idx": 0.0,
      "iraq_signals": 0,
      "iraq_idx": 0.0,
      "armenia_signals": 0,
      "bulgaria_idx": 0.0,
      "iran_signals": 0,
      "status": NaN,
      "bulgaria_signals": 0
    },
    {
      "timestamp": "2026-01-15T10:41:56.992459",
      "index": NaN,
      "main_index": 6.39,
      "georgia_idx": 1.0,
      "georgia_signals": 3,
      "syria_signals": 10,
      "greece_signals": 15,
      "syria_idx": 4.22,
      "total_signals": 76,
      "greece_idx": 3.56,
      "armenia_idx": 3.61,
      "iran_idx": 4.21,
      "iraq_signals": 15,
      "iraq_idx": 2.78,
      "armenia_signals": 10,
      "bulgaria_idx": 3.81,
      "iran_signals": 8,
      "status": "ELEVATED",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-15T12:44:57.499200",
      "index": NaN,
      "main_index": 6.24,
      "georgia_idx": 1.0,
      "georgia_signals": 4,
      "syria_signals": 10,
      "greece_signals": 15,
      "syria_idx": 1.7,
      "total_signals": 78,
      "greece_idx": 4.37,
      "armenia_idx": 3.31,
      "iran_idx": 4.47,
      "iraq_signals": 15,
      "iraq_idx": 3.54,
      "armenia_signals": 10,
      "bulgaria_idx": 2.88,
      "iran_signals": 9,
      "status": "ELEVATED",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-15T23:32:37.368792",
      "index": NaN,
      "main_index": 7.57,
      "georgia_idx": 3.63,
      "georgia_signals": 7,
      "syria_signals": 10,
      "greece_signals": 15,
      "syria_idx": 4.53,
      "total_signals": 83,
      "greece_idx": 4.64,
      "armenia_idx": 1.0,
      "iran_idx": 5.17,
      "iraq_signals": 15,
      "iraq_idx": 5.76,
      "armenia_signals": 10,
      "bulgaria_idx": 4.87,
      "iran_signals": 11,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T00:34:17.555514",
      "index": NaN,
      "main_index": 7.35,
      "georgia_idx": 3.63,
      "georgia_signals": 4,
      "syria_signals": 10,
      "greece_signals": 15,
      "syria_idx": 4.53,
      "total_signals": 75,
      "greece_idx": 3.28,
      "armenia_idx": 1.0,
      "iran_idx": 4.77,
      "iraq_signals": 15,
      "iraq_idx": 5.76,
      "armenia_signals": 10,
      "bulgaria_idx": 4.87,
      "iran_signals": 6,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T00:48:15.880253",
      "index": NaN,
      "main_index": 7.45,
      "georgia_idx": 3.63,
      "georgia_signals": 4,
      "syria_signals": 10,
      "greece_signals": 15,
      "syria_idx": 4.53,
      "total_signals": 75,
      "greece_idx": 4.36,
      "armenia_idx": 1.0,
      "iran_idx": 4.77,
      "iraq_signals": 15,
      "iraq_idx": 5.76,
      "armenia_signals": 10,
      "bulgaria_idx": 4.87,
      "iran_signals": 6,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T11:43:18.762284",
      "index": NaN,
      "main_index": 7.39,
      "georgia_idx": 3.63,
      "georgia_signals": 5,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 4.39,
      "total_signals": 87,
      "greece_idx": 4.25,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.46,
      "armenia_signals": 15,
      "bulgaria_idx": 5.16,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T08:57:24.453249",
      "index": NaN,
      "main_index": 7.32,
      "georgia_idx": 3.63,
      "georgia_signals": 5,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 4.39,
      "total_signals": 87,
      "greece_idx": 4.16,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.46,
      "armenia_signals": 15,
      "bulgaria_idx": 4.93,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T09:30:38.052756",
      "index": NaN,
      "main_index": 7.34,
      "georgia_idx": 3.63,
      "georgia_signals": 5,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 4.38,
      "total_signals": 87,
      "greece_idx": 4.16,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.87,
      "armenia_signals": 15,
      "bulgaria_idx": 4.67,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T10:21:01.803849",
      "index": NaN,
      "main_index": 7.13,
      "georgia_idx": 3.63,
      "georgia_signals": 6,
      "syria_signals": 13,
      "greece_signals": 15,
      "syria_idx": 3.03,
      "total_signals": 86,
      "greece_idx": 4.16,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.87,
      "armenia_signals": 15,
      "bulgaria_idx": 4.18,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T11:05:15.784506",
      "index": NaN,
      "main_index": 7.42,
      "georgia_idx": 4.23,
      "georgia_signals": 7,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 4.97,
      "total_signals": 89,
      "greece_idx": 4.43,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.87,
      "armenia_signals": 15,
      "bulgaria_idx": 3.71,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T11:23:53.434438",
      "index": NaN,
      "main_index": 7.29,
      "georgia_idx": 4.23,
      "georgia_signals": 7,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 4.25,
      "total_signals": 89,
      "greece_idx": 4.43,
      "armenia_idx": 4.22,
      "iran_idx": 4.89,
      "iraq_signals": 15,
      "iraq_idx": 4.79,
      "armenia_signals": 15,
      "bulgaria_idx": 3.71,
      "iran_signals": 7,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T11:37:37.503632",
      "index": NaN,
      "main_index": 7.44,
      "georgia_idx": 4.23,
      "georgia_signals": 8,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.39,
      "total_signals": 90,
      "greece_idx": 4.43,
      "armenia_idx": 3.47,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 3.93,
      "armenia_signals": 10,
      "bulgaria_idx": 4.18,
      "iran_signals": 12,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T11:49:40.787683",
      "index": NaN,
      "main_index": 7.04,
      "georgia_idx": 4.23,
      "georgia_signals": 8,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 1.73,
      "total_signals": 90,
      "greece_idx": 4.43,
      "armenia_idx": 3.47,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 3.93,
      "armenia_signals": 10,
      "bulgaria_idx": 4.18,
      "iran_signals": 12,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T12:47:14.602448",
      "index": NaN,
      "main_index": 7.44,
      "georgia_idx": 4.23,
      "georgia_signals": 7,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.39,
      "total_signals": 89,
      "greece_idx": 3.84,
      "armenia_idx": 3.47,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 4.78,
      "armenia_signals": 10,
      "bulgaria_idx": 3.72,
      "iran_signals": 12,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T13:33:23.915882",
      "index": NaN,
      "main_index": 7.4,
      "georgia_idx": 4.23,
      "georgia_signals": 8,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.11,
      "total_signals": 90,
      "greece_idx": 4.18,
      "armenia_idx": 3.47,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 4.73,
      "armenia_signals": 10,
      "bulgaria_idx": 3.74,
      "iran_signals": 12,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T13:44:53.544621",
      "index": NaN,
      "main_index": 6.95,
      "georgia_idx": 4.23,
      "georgia_signals": 8,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 1.0,
      "total_signals": 90,
      "greece_idx": 4.18,
      "armenia_idx": 3.47,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 4.73,
      "armenia_signals": 10,
      "bulgaria_idx": 3.46,
      "iran_signals": 12,
      "status": "ELEVATED",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T14:28:31.849885",
      "index": NaN,
      "main_index": 7.56,
      "georgia_idx": 4.23,
      "georgia_signals": 9,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.11,
      "total_signals": 91,
      "greece_idx": 5.03,
      "armenia_idx": 3.25,
      "iran_idx": 5.26,
      "iraq_signals": 15,
      "iraq_idx": 4.98,
      "armenia_signals": 10,
      "bulgaria_idx": 3.73,
      "iran_signals": 12,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T14:54:21.959482",
      "index": NaN,
      "main_index": 7.75,
      "georgia_idx": 4.95,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.81,
      "total_signals": 90,
      "greece_idx": 5.03,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.48,
      "armenia_signals": 15,
      "bulgaria_idx": 4.9,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T15:31:37.529359",
      "index": NaN,
      "main_index": 7.6,
      "georgia_idx": 4.6,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.56,
      "total_signals": 90,
      "greece_idx": 4.93,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.62,
      "armenia_signals": 15,
      "bulgaria_idx": 4.61,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T16:33:26.646415",
      "index": NaN,
      "main_index": 7.16,
      "georgia_idx": 4.01,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.17,
      "total_signals": 90,
      "greece_idx": 2.44,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 4.98,
      "armenia_signals": 15,
      "bulgaria_idx": 5.33,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T17:30:43.683947",
      "index": NaN,
      "main_index": 7.19,
      "georgia_idx": 5.11,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.03,
      "total_signals": 90,
      "greece_idx": 2.44,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.03,
      "armenia_signals": 15,
      "bulgaria_idx": 4.73,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T18:43:06.979410",
      "index": NaN,
      "main_index": 7.18,
      "georgia_idx": 5.11,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.18,
      "total_signals": 90,
      "greece_idx": 2.44,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.18,
      "armenia_signals": 15,
      "bulgaria_idx": 4.22,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T19:26:24.319123",
      "index": NaN,
      "main_index": 7.17,
      "georgia_idx": 4.01,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.56,
      "total_signals": 90,
      "greece_idx": 3.93,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.18,
      "armenia_signals": 15,
      "bulgaria_idx": 3.95,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T20:29:01.472563",
      "index": NaN,
      "main_index": 7.25,
      "georgia_idx": 5.01,
      "georgia_signals": 15,
      "syria_signals": 15,
      "greece_signals": 15,
      "syria_idx": 5.31,
      "total_signals": 90,
      "greece_idx": 3.93,
      "armenia_idx": 3.02,
      "iran_idx": 1.0,
      "iraq_signals": 15,
      "iraq_idx": 5.31,
      "armenia_signals": 15,
      "bulgaria_idx": 3.44,
      "iran_signals": 0,
      "status": "CRITICAL",
      "bulgaria_signals": 15
    },
    {
      "timestamp": "2026-01-16T21:25:31.320857",
      "index": 7.36,
      "type": "live"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-01-16T22:25:37.124282",
      "index": 7.37,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-16T23:25:37.124282",
      "index": 7.37,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-17T00:25:37.124282",
      "index": 7.38,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-17T01:25:37.124282",
      "index": 7.39,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-17T02:25:37.124282",
      "index": 7.39,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-17T03:25:37.124282",
      "index": 7.4,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "Modified Goldstein Scale",
    "description": "AI-powered threat classification using XLM-RoBERTa multilingual model with category-weighted scoring",
    "weights": {
      "military conflict": 10.0,
      "terrorist act": 9.0,
      "violent protest": 7.0,
      "political crisis": 6.0,
      "economic crisis": 4.0,
      "humanitarian crisis": 3.0,
      "peaceful diplomacy": -2.0,
      "neutral news": 0.0
    },
    "formula": "ThreatIndex = log10(1 + Σ(category_weight × confidence)) × 3.5",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  }
};