window.BNTI_DATA = {
  "meta": {
    "generated_at": "2026-01-30T23:36:25.808472",
    "main_index": 7.94,
    "status": "CRITICAL",
    "active_scan": true,
    "next_update": "2026-01-31T00:00:00",
    "version": "2.0.0"
  },
  "countries": {
    "Armenia": {
      "index": 3.54,
      "raw_score": 9.28,
      "events": [
        {
          "title": "Newsom fights back after Dr Oz accuses LA’s Armenians of healthcare fraud - The Guardian",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxQQ1kyYThqdlYxdWJZUk8yVWhDOVNIN3prQVRXdVAyc2dzWlRkUTlWS2VNd1ZObnpSUG9jalZhclg1TkhDdXRyUVp5b09WRl91X1ltd3JKOU0xRkI2dkNWVHo5aDd2V3lMcVhhVWVqRkRlX0llWUJIWXhhWS1VaVRKeFd4TGhaSXFnbEcw?oc=5",
          "date": "Fri, 30 Jan 2026 15:18:00 GMT",
          "category": "violent protest",
          "confidence": 0.8049412369728088,
          "weight": 5.634588658809662,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "80.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Newsom files civil rights complaint accusing Dr. Oz of targeting Armenian Americans - CBS News",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxQTG8xNjlNZ2ozbGE3aXVVd1lXVmdiZzlOU0NfMkZyRXhsUGVhRGxEX0VGR0Fmc2MzSVlnV0FrdXNEeUdSQ1gtelczZm40b2Zfc3huZjVJQnRaU2xUY19YZWVldTUtQno4aXpuclhYQkpNTkZIZEw5dFlGblExa2hhZVlGWFZzQzFzdE9LbmZkTW5TdWJFZTc1eV9EeEQtRTY4VHp5c2RUN3lsTmFvMllNY21TcEdrZFF4V1I0cFk1MnI?oc=5",
          "date": "Fri, 30 Jan 2026 06:21:39 GMT",
          "category": "political crisis",
          "confidence": 0.6425858736038208,
          "weight": 3.855515241622925,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "64.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "\"I'm Against Everyone\" Movement Seeks Upset Win in Armenia's June Parliamentary Election - Hetq.am",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE1LNk5HRFFXMkI1VWhqUk9EMTNTZDYzNDZtazBMLU1lbTdiTnJJR19aTXFSa1lvS3lQVlVmYlpkV2dzQzM4RnhSZw?oc=5",
          "date": "Thu, 29 Jan 2026 09:15:00 GMT",
          "category": "political crisis",
          "confidence": 0.5015178918838501,
          "weight": 3.0091073513031006,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "50.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Kocharyan Says He's Front-Runner to Head Hayastan Alliance in Armenia's June Parliamentary Election - Hetq.am",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiSEFVX3lxTE80UjJmSkdlZDA3bHFBXzV3dUtTZHI1R21LSjdkbWc1YUVjbjA2VTlsNHVBX1lwc2QtSzE2TkxmQzF2bWpGNmt3LQ?oc=5",
          "date": "Thu, 29 Jan 2026 08:00:00 GMT",
          "category": "violent protest",
          "confidence": 0.30979952216148376,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "EU to Allocate €20 Million in Military Aid to Armenia - Мілітарний",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMijgFBVV95cUxOQ3dSS3pGQTMxTEpLV0lFMllGSG5GWEtJTkQzRGhkVXBlYjlGRS02UmJTam4ya29FRVpacGo0REVhS0UyenFQVWNaa2Roa3lmR292QnhPbXV6NUYyZHYwOXZRQlRPcmtLNEhEMWRRS0tfM2RzbERnY2hMSXZBOTRld0h6N0QtcFJBUWFyOW5B?oc=5",
          "date": "Thu, 29 Jan 2026 12:22:28 GMT",
          "category": "violent protest",
          "confidence": 0.38276243209838867,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "38.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Pashinyan backs linking Armenia’s energy grid with Türkiye, Azerbaijan | Daily Sabah - Daily Sabah",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxQM0NXMl9iMmZiWlAzbnYzem9IelZLallWSFM4LUIzNVlzMGZsaDN5Tk5CdjJXS3ZOaVJPbjR2ZXVEYzFRQlg3MlpONVlCMWo2VWRBSE14SnlBMlNqcjZwd1R1TlRhdFdMLTAyU3RZYVhqVktmbXYwMTNMblRkLW4tcFlNNi1SN201SjE1LXZ3bXlhb2FBVzlXMDJZQVpocEMxZThkaFoxY3VwVG1TaWFpN9IBtgFBVV95cUxQS0JXWE1ONGluR2Q4WTllcV9rU3JlMzR6ejlHT2lHZlR1QVFpOU5MQWpITTR0dWkyeHpaOXhiMzE2dG9mTGd6emoteDVvOEtZd25ZbTM1RWRoWWtiRGpyM05uUlFvTzRxbUZZNVNEN1l4V25nSGZWaDdQQlM0WjJyVmxFYzVsUHhuMTZkQkxSSDhnbS1weXd2d3AteU9JNjI4eC1TelBqcmRtbjBKUUctbUFqUW1sUQ?oc=5",
          "date": "Thu, 29 Jan 2026 15:23:00 GMT",
          "category": "neutral news",
          "confidence": 0.5672203898429871,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "56.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Leaked Russian report details influence strategy for diaspora in South Caucasus - OC Media",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxPTkQwQTR0WVFtNlEwNWdYXzRJUC1kOHhlUzl5aHJUc2NzQnd1YW9HYmwwVEM4WkZEM3NBakhSYUNlQ0JJQ1RxX3lYRDhlVjBPUk1kYjhzWWRPcTA1b19qdFhqT2pKTWZKRTRxR0FUc0FwOWFraHVvYnpLcEJNRnV2OXZaU25Pcnc1QTBoLUNzRkYwbXY1WDhQVExMVjVsQmVBc0Nn?oc=5",
          "date": "Fri, 30 Jan 2026 05:47:43 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.3070867955684662,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Moscow Repeats Interest In ‘Trump Route’ Through Armenia - Ազատություն Ռադիոկայան",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiUkFVX3lxTE85TVlucE9tQUVRNzJHWDdTQVRWbWlnRlV5ckh2TERvVERsSXBiOXhXblBGNU5FUm5WdEI3MEQzMzB2Ql9UenZZdXVLWnRHOW9ENlHSAVRBVV95cUxNVWJQREhZbG5DUXE4LU5FaVZydHZRcHVvbTBwRm94dWx4UGw4RUFjWUJpUjVYMUJGOVVKaGN4Y3BjNlZLZFVkanpCQWpKb01VNFE0UDU?oc=5",
          "date": "Fri, 30 Jan 2026 17:33:06 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.17719820141792297,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Recently Transferred Karabakh Armenians Allegedly Unaware They Were Being Sent to Armenia - The Armenian Mirror-Spectator",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiyAFBVV95cUxQLWhGRml5c0hQY2ZRazduajZIRW1OVjJiXzlsVFNvY1pEeHJmTnJUME8tNUJwbmFEam5fX1Mwbjl3WmNVZ19leHFEY3JiUGVNQ2FFTGt2aVFELXRLSmRka3V0TGZ5dVRUNjlTTElqRDJ4U245MHQzTHRaVG95elN6SnZxNmJ1WnhVVG9qMU0xVzhMVTNraF9YU2ZhVk5ZUnM4eklfTVhuQUk1bFFmQ2VUMGowQ09ET3MwcU1xOGxiYzNWVGExSmt5ZQ?oc=5",
          "date": "Thu, 29 Jan 2026 12:05:48 GMT",
          "category": "neutral news",
          "confidence": 0.1838596910238266,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armenia’s Security Dilemma: Seeking Shelter in a Fractured West - Modern Diplomacy",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxOWmFtNzdnY3dBVnBBWnVhdEFkWW43SFNkWnlpenE1SkpNQlhveDVTQkF3NlRuNlppaXlXOGF5NzZVVVE1WVZEQVlUMV9XaE9FV21QS3VndVRuRmJLNUloNU43TEIzb0xra1k3d2hqX05DbWJwWnhxNElsMzYyNnNtd0xhLWtkMGx5c1pYQklXaFlyR01kOXR0bXQzYmZaVGxSOHc?oc=5",
          "date": "Fri, 30 Jan 2026 23:00:32 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.36377787590026855,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "36.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Opinion: oligarch Samvel Karapetyan’s party ‘Strong Armenia’ will represent Russian interests - JAMnews",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPa3NJZWdhQ3lLZ1BfN3VtRnU3Njl0Rk9XSnVhR2JLOUJhNDdLNlNucjNfLW11bFFRejU4UjZpemtoRVpvTjRzaXd6OXg0YXNXOGFMM2d4clJETEZLSXBpWEUzYlpUdkhJNWJSaGFKdDl6bFhXQ3NQWVNvQm5RQnZnOEIwRnNCOTR2c2ZMVTl5LTZEWGNSdXZsSXFOUlVsTlptcXE4UW1XWkJzSUplcWpRYw?oc=5",
          "date": "Fri, 30 Jan 2026 19:03:41 GMT",
          "category": "political crisis",
          "confidence": 0.23039919137954712,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.0%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Dr. Oz’s anti-Armenian smear in LA fits a pattern - San Francisco Chronicle",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMisAFBVV95cUxPOGxpcC0yUDcwQTY1ODNwWDl6bmJ2Z05fdno2bkczMkNXLU1YdnhfTUx3d0o4eUhCam4xaGU2NU95QnhmdVRya2N1a2c5WVVBWGhKeGQ3WjhaLVlWV0pfdTRWXy1ra3h1Z284X2VEaXBOVUY3cFBka2JaZHluQmFHUVRFU1VGNGZRdW9jaHVnYXhGVklRRlh1UFR6Z0RrVnE0bV8ySFpKWWNHdFd3VHZ3YQ?oc=5",
          "date": "Fri, 30 Jan 2026 18:42:45 GMT",
          "category": "neutral news",
          "confidence": 0.22600995004177094,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Russia’s Foreign Ministry again bashes Armenia’s EU aspirations - OC Media",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiwFBVV95cUxNLXRuQTNMdTZxRkhraEZUcTRpQ3lqZFJleEdFdi1PTnFSZWxYdHdPalJqb2ItTEtpVUY2RHY2WmpVRzQ1NVhCY1N0azZSbGZ0eXZBNUxKdVBjb1RKaEZEZTk1NkZqRGdsaFViNWNMME9YTnpJbVJXdWQxVnNKRDNFS2hLZXlOamdjRHRj?oc=5",
          "date": "Fri, 30 Jan 2026 09:14:48 GMT",
          "category": "political crisis",
          "confidence": 0.17471815645694733,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Trump Wants “Peace Through Construction.” There’s One Place It Could Actually Work. - Carnegie Endowment for International Peace",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMilAFBVV95cUxQbDVXQ243dWlnb1F5Z3pQTGk5TGdiaGZVSlYzVU5WOG45N3FzV0hJQW5nekFQdjNHOWlDaHJ4VnFGQWtwWlZqRVgyc0NDM2hteWUyX0RqaF82Z3Fxel9RNmNCZ1l6TW80NWNqWTNLRGFsc0dXZ29aQXJCUjhFcGg4a3o2WmsyNURQdmZVYXAtUDlDUnNR?oc=5",
          "date": "Fri, 30 Jan 2026 23:08:48 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.6605284810066223,
          "weight": -1.3210569620132446,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "66.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        },
        {
          "title": "Armen Rustamyan: PACE has its own priorities, and they fully align with supporting Armenia’s current authorities - The Armenian Weekly",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi4gFBVV95cUxOOXJFNkM0MHB2MXdpZVNIanJJdjlEZU5jb0dsZHVDZTVwcFNmSVFRSWdEVEczaFlKUjhZUkZxaTJ4OVBXakFiTXhJNlZJeVhFNnowVkVYNUp6N0lxUGtLRTB5YU5oRDZPM1E3d3JmRXM1Zk9xU05hT3VYN3pnelRQUnBkOWJaZDZibnVYbUZLZnNOd0hsY2pkcnBXWm5kelpXMWdKQVVpR2RwX3ZVMEJ2VmdBSnpCQTdBWjJBU0ZmTGNqcnR2UEJ1ZW1uU3NNQmxSc01sVjJYaG95Unl6NTdrTlZn?oc=5",
          "date": "Thu, 29 Jan 2026 14:38:05 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.9475129246711731,
          "weight": -1.8950258493423462,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "94.8%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Armenia"
        }
      ]
    },
    "Georgia": {
      "index": 5.35,
      "raw_score": 32.88,
      "events": [
        {
          "title": "Analysis | Checking Georgia’s Anti-EU Drift - Civil Georgia",
          "translated_title": "Analysis | Checking Georgia’s Anti-EU Drift - Civil Georgia",
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE9rWUNrMkRfV1BqQXJhOVhESnBVSTlubXBDLW90MDRLMWdWa0t2d1BhU2VxaEdvUWFrdkdwZU5oYlVVTEtLWXNV0gFMQVVfeXFMT0ZPUE53LXQ2ZXBtNzVSUFlLWGZIMWVROE4yU3MwaUVkZE9lLVlpSGwzZzJ2NUJMZ0NhQm9zUXE2S1dGVHZ4LWY0cnJ4Qw?oc=5",
          "date": "Fri, 30 Jan 2026 11:21:08 GMT",
          "category": "political crisis",
          "confidence": 0.9640584588050842,
          "weight": 5.784350752830505,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.4%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Analysis | Checking Georgia’s Anti-EU Drift",
          "translated_title": "Analysis | Checking Georgia’s Anti-EU Drift",
          "link": "https://civil.ge/archives/718545",
          "date": "Fri, 30 Jan 2026 11:21:08 +0000",
          "category": "political crisis",
          "confidence": 0.9528886675834656,
          "weight": 5.7173320055007935,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.3%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Georgia",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "24 Countries Invoke OSCE Moscow Mechanism on Georgia - Civil Georgia",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE5xU1FBcHQyV1JjT1dZTXpUMURSdkdVbThuaUlfRHJRc3BLZk1NRWtfd2VGcmpVdVhJV0p3VkN0Q0NLSzN5MGpv0gFMQVVfeXFMTThBOEVzbkZTWGVrMkpadlYtWmtyRVk1QUE5NG1qV0cySmpJNkMtdDNjT0pzOG4yN2o0R3FlTGNuTUoxWXlrT2FXQm8tUQ?oc=5",
          "date": "Thu, 29 Jan 2026 14:29:08 GMT",
          "category": "political crisis",
          "confidence": 0.7231279611587524,
          "weight": 4.338767766952515,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "72.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Students from 100 GA schools part of National Shutdown despite warnings - USA Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMixgFBVV95cUxPYl83a1RsTkdnRFNCYk84bUgxYXdNWVdDMVhHRTdWb2VTYURQSmc5dGJsY3haclVsYktVdHJDdUNWR0xHTHYtVlpqdjhUT0lGelNyNGhJenFBU3JKZU1oT1BGQ2Q1azF4cF82cTdPWnhfUmY1QzJvR2hmNEdBWkRJd3diWW1YcXh3VjRQR2o0SkFzUndZTXVBOS1SVVlqU2FPb1FDd3hKekRQTDF6YVpSQTJGb0VOVFBOdVpkUEgyXzF0bW53Z0E?oc=5",
          "date": "Fri, 30 Jan 2026 14:55:00 GMT",
          "category": "violent protest",
          "confidence": 0.5643845200538635,
          "weight": 3.9506916403770447,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "56.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgian Technical University to Be Merged with Tbilisi State University - Civil Georgia",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE5ZQmxvMkZYS1htX0RhNS1uTWlYUEMwQmV4LWJoZnBFRnpnRml4V1V4Z2RtSDd1Um5NRlFjeGxTUzZrcUl5ZW530gFMQVVfeXFMTVg2LUhmNW9UcmhGN3BmM3o4SzVSQjR4eEl4WHRtV0UyWVhqejI1WUxLSXBnZkpEYnEweEhxRmgxYkI0clhYbFJRNVBkbQ?oc=5",
          "date": "Thu, 29 Jan 2026 08:26:01 GMT",
          "category": "political crisis",
          "confidence": 0.6462022662162781,
          "weight": 3.8772135972976685,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "64.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Russian Duma Member Claims Contacts with Georgian MPs - Civil Georgia",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiR0FVX3lxTE9OREFxazlJMFBUSUFwNzh0Tm1QVkk5d0ZnczVfUmhRc093UG0zZGl2NmxGaFNVWmduWi1QVnhLMXFackZzWUlJ0gFMQVVfeXFMUGFHYWxFbldDTXNZZEFPSTZjTXk4eEZDTlJLU2xNUEVwSE1uMFMzbmtDNEl4NHVJS2s3YTV1V2g3eHRHQUx5MFdqLVVQUA?oc=5",
          "date": "Fri, 30 Jan 2026 09:27:48 GMT",
          "category": "political crisis",
          "confidence": 0.5448748469352722,
          "weight": 3.2692490816116333,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "54.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "24 OSCE countries have invoked the Moscow Mechanism in connection with human rights violations in Georgia. - Caucasian Knot",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiWEFVX3lxTFA5M3ZKalJqazJoWGdub2Z6ZWlsM3Ftc0pVSVFRNlpER0NSNlhkbThaZ1IxS19RUV9OUjhBWXZCaHBqOTZaQ0VmYUtnSHhveGpBYzgyS3V2ejE?oc=5",
          "date": "Fri, 30 Jan 2026 02:03:45 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.9914551377296448,
          "weight": 2.9743654131889343,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "99.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "24 OSCE countries back investigation into Georgia over deteriorating human rights - JAMnews",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMibkFVX3lxTE9lTGdSV0RPSG5jdUxmRXFOZ1JNV1dCT1h2dWNCdm01c1FXamNVU0Nndl9sYWZONFNEUlVmLTN3U3N6N1FwRURaUzJfZUJ0MlNPdmNQT2wxVkFFWmxoclRJNVhsUEFtM3BfWU01VDh3?oc=5",
          "date": "Thu, 29 Jan 2026 17:29:08 GMT",
          "category": "humanitarian crisis",
          "confidence": 0.9884995818138123,
          "weight": 2.9654987454414368,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "98.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Tulsi Gabbard under scrutiny for showing up at FBI raid of Georgia election hub - NBC News",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMivwFBVV95cUxNeS1NV3FEajJ4LTZLQ3RHM25QYjBXX2NZVXZSRnZuR0RDNkVLSGRVWGdSQ0lITnQ3RGJFTGxnaEkweS1OT1R1SHVVazVCVDdZNHRWNkdhVS1aeFUxZTFwbHIySTYwTmtTM2pEejBCbFg5d2d3b0F5UXd2RFFNQnB6MmFmY1ZpZnZ1UTVRQlBHckxWblQ3cjhhTzdDdDFXSkVtdHV2MTJBZFNjb0lFSmxHdE5yRW9wZGxPdVZfRTdTSQ?oc=5",
          "date": "Fri, 30 Jan 2026 02:09:00 GMT",
          "category": "political crisis",
          "confidence": 0.41278505325317383,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "41.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia's national championship odds show people love throwing money away shamelessly - Dawn of the Dawg",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxNUE0yV1RNNWM4eVQzYUhwUkY3eHYzdDZzRW1qNmNiWHZ2cFBIUG5JRHljekJvVmFRdU5Yc21LRUZfYmFwVmNiVzcxSXNjX1J2T0xMTDBPM1V0ZVdYN2pxM0FNMHhaeUg0eTVzS1pvTnJiUFRuOXhXd2wyMlU4bU9JUUVLOHFyTy1oV25WNldNQmV0d2lWX0Z2OVk3MU1paEI4ZGdra2F1VXl3bGhBNGc?oc=5",
          "date": "Thu, 29 Jan 2026 21:52:57 GMT",
          "category": "neutral news",
          "confidence": 0.25832459330558777,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Students from Georgia's largest universities held a protest in Tbilisi. - Caucasian Knot",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE5sM3gxdTNLLTExNkJZS0swLWM3OFNfUGphTE92eWd0amdJbnMzckQyMmxIYU9rZzZWY0taNUxaak1kRjBrQ0JoSGMwOVF2NDR3UDJfeE1RcFI?oc=5",
          "date": "Thu, 29 Jan 2026 20:48:45 GMT",
          "category": "neutral news",
          "confidence": 0.18273678421974182,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "130th IPRM Meeting Held in Ergneti",
          "translated_title": null,
          "link": "https://civil.ge/archives/719435",
          "date": "Fri, 30 Jan 2026 10:10:00 +0000",
          "category": "neutral news",
          "confidence": 0.2523871660232544,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Russian Duma Member Claims Contacts with Georgian MPs",
          "translated_title": null,
          "link": "https://civil.ge/archives/719360",
          "date": "Fri, 30 Jan 2026 09:27:48 +0000",
          "category": "political crisis",
          "confidence": 0.2884769141674042,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "28.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "Georgia’s GDP Up by 7.5% in 2025",
          "translated_title": null,
          "link": "https://civil.ge/archives/719416",
          "date": "Fri, 30 Jan 2026 08:33:21 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.25518158078193665,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Georgia"
        },
        {
          "title": "24 Countries Invoke OSCE Moscow Mechanism on Georgia",
          "translated_title": null,
          "link": "https://civil.ge/archives/719361",
          "date": "Thu, 29 Jan 2026 14:29:08 +0000",
          "category": "violent protest",
          "confidence": 0.16345307230949402,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "16.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Georgia"
        }
      ]
    },
    "Greece": {
      "index": 1.15,
      "raw_score": 1.13,
      "events": [
        {
          "title": "To «Warsh Effect» κλόνισε τη Wall Street - Απώλειες σε όλους τους δείκτες",
          "translated_title": null,
          "link": "https://www.protothema.gr/economy/article/1766199/to-warsh-effect-klonise-ti-wall-street-apoleies-se-olous-tous-deiktes/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:18:00 +0200",
          "category": "economic crisis",
          "confidence": 0.4708413779735565,
          "weight": 1.883365511894226,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "47.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ελεύθερος χωρίς εγγύηση ο Ντον Λέμον - Κατηγορείται για παρεμπόδιση θρησκευτικής λατρείας",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1766207/eleutheros-horis-egguisi-o-don-lemon-katigoreitai-gia-parebodisi-thriskeutikis-latreias/?utm_source=rss",
          "date": "Sat, 31 Jan 2026 01:20:00 +0200",
          "category": "neutral news",
          "confidence": 0.3054911494255066,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.5%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Σεισμός 3 Ρίχτερ στα Χανιά",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1766206/seismos-3-rihter-sta-hania/?utm_source=rss",
          "date": "Sat, 31 Jan 2026 01:11:00 +0200",
          "category": "violent protest",
          "confidence": 0.2438177466392517,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Με 13 ψήφους υπέρ και δύο αποχές υιοθετήθηκε το ψήφισμα του Συμβουλίου Ασφαλείας για την ανανέωση της ΟΥΝΦΙΚΥΠ",
          "translated_title": null,
          "link": "https://www.protothema.gr/politics/article/1766205/me-13-psifous-uper-kai-2-apohes-uiothetithike-to-psifisma-tou-sumvouliou-asfaleias-gia-tin-ananeosi-tis-ounfikup/?utm_source=rss",
          "date": "Sat, 31 Jan 2026 00:50:00 +0200",
          "category": "neutral news",
          "confidence": 0.42437314987182617,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Άταμαν: Στα τελευταία δύο λεπτά κάναμε ντροπιαστικά λάθη, κάποιοι παίκτες δεν μπορούν να παίζουν σε αυτό το επίπεδο",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1766204/ataman-sta-teleutaia-duo-lepta-kaname-dropiastika-lathi-kapoioi-paiktes-den-boroun-na-paizoun-se-auto-to-epipedo/?utm_source=rss",
          "date": "Sat, 31 Jan 2026 00:41:00 +0200",
          "category": "neutral news",
          "confidence": 0.2274855673313141,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Η κατάταξη στη EuroLeague μετά τη νίκη του Παναθηναϊκού",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1766203/i-katataxi-sti-euroleague-meta-ti-niki-tou-panathinaikou/?utm_source=rss",
          "date": "Sat, 31 Jan 2026 00:17:00 +0200",
          "category": "peaceful diplomacy",
          "confidence": 0.31331154704093933,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "31.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ξέσπασε ο Σπανούλης για την κατάσταση στη Μονακό: Πρέπει να βρεθεί λύση, δεν είναι φυσιολογικό όλο αυτό",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1766202/xespase-o-spanoulis-gia-tin-katastasi-sti-monako-prepei-na-vrethei-lusi-den-einai-fusiologiko-olo-auto/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:52:00 +0200",
          "category": "neutral news",
          "confidence": 0.23354081809520721,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Κονγκό: Τουλάχιστον 200 νεκροί από κατάρρευση ορυχείου που ελέγχουν οι αντάρτες",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1766201/kongo-toulahiston-200-nekroi-apo-katarreusi-oruheiou-pou-eleghoun-oi-adartes/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:41:00 +0200",
          "category": "military conflict",
          "confidence": 0.4034065306186676,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "40.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "«Νομίζω πως έχω καεί»: Συγκλονίζουν τα ηχητικά ντοκουμέντα από τη νύχτα της τραγωδίας στο Κραν Μοντανά",
          "translated_title": null,
          "link": "https://www.protothema.gr/world/article/1766200/nomizo-pos-eho-kaei-suglonizoun-ta-ihitika-dokoumeda-apo-ti-nuhta-tis-tragodias-sto-kran-modana/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:25:00 +0200",
          "category": "violent protest",
          "confidence": 0.3394915461540222,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ερυθρός Αστέρας-Dubai BC 95-92: Τέσσερις σερί νίκες για τους Σέρβους",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1766198/eruthros-asteras-dubai-bc-95-92-tesseris-seri-nikes-gia-tous-servous/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:15:00 +0200",
          "category": "violent protest",
          "confidence": 0.25051000714302063,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Σε δημόσια διαβούλευση το σχέδιο νόμου για την επιστολική ψήφο των Ελλήνων του εξωτερικού",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1766197/se-dimosia-diavouleusi-to-shedio-nomou-tou-upourgeiou-esoterikon-gia-tin-psifo-ton-apodimon-meso-epistolikis-psifou/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:11:00 +0200",
          "category": "political crisis",
          "confidence": 0.1770085245370865,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "17.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ευγενία Σαμαρά: Δεν είμαι ούτε κοντά ούτε μακριά από τη μητρότητα, η ζωή ξέρει καλύτερα αν θα μου φέρει ένα παιδί",
          "translated_title": null,
          "link": "https://www.protothema.gr/life-style/article/1766196/eugenia-samara-den-eimai-oute-koda-oute-makria-apo-ti-mitrotita-i-zoi-xerei-kalutera/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:45:00 +0200",
          "category": "neutral news",
          "confidence": 0.452603816986084,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Νικολέτα Βλαβιανού: Ποτέ δεν έβγαλα πολλά λεφτά, καμιά δεκαριά ηθοποιοί έβγαλαν από την τηλεόραση",
          "translated_title": null,
          "link": "https://www.protothema.gr/life-style/article/1766192/nikoleta-vlavianou-pote-den-evgala-polla-lefta-kamia-dekaria-ithopoioi-evgalan-apo-tin-tileorasi/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 23:03:01 +0200",
          "category": "violent protest",
          "confidence": 0.3262633979320526,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "32.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Έρευνες των Αρχών για διακίνηση πλαστών χαρτονομισμάτων στην Κρήτη",
          "translated_title": null,
          "link": "https://www.protothema.gr/greece/article/1766190/ereunes-ton-arhon-gia-diakinisi-plaston-hartonomismaton-ston-agio-nikolao/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 22:59:00 +0200",
          "category": "military conflict",
          "confidence": 0.24186936020851135,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        },
        {
          "title": "Ο Βιλντόζα εκτέλεσε τη Μονακό: Με τρίποντο στα 4'' η Βίρτους 84-82 την ομάδα του Σπανούλη στο Πριγκιπάτο, βίντεο",
          "translated_title": null,
          "link": "https://www.protothema.gr/sports/article/1766182/o-vildoza-ektelese-ti-monako-me-tripodo-sta-4-i-virtous-84-82-tin-omada-tou-spanouli-sto-prigipato-video/?utm_source=rss",
          "date": "Fri, 30 Jan 2026 22:47:00 +0200",
          "category": "violent protest",
          "confidence": 0.36170071363449097,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "36.2%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Greece"
        }
      ]
    },
    "Iran": {
      "index": 5.51,
      "raw_score": 36.63,
      "events": [
        {
          "title": "Trump warns Iran 'time is running out' for nuclear deal as US military builds up in Gulf",
          "translated_title": "Trump warns Iran 'time is running out' for nuclear deal as US military builds up in Gulf",
          "link": "https://www.bbc.com/news/articles/cly5pd459gko?at_medium=RSS&at_campaign=rss",
          "date": "Thu, 29 Jan 2026 05:47:03 GMT",
          "category": "military conflict",
          "confidence": 0.9598000645637512,
          "weight": 9.598000645637512,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "96.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Israeli media cite official accepting Hamas figure of 70,000 war dead",
          "translated_title": "Israeli media cite official accepting Hamas figure of 70,000 war dead",
          "link": "https://www.bbc.com/news/articles/cvgpd1x00exo?at_medium=RSS&at_campaign=rss",
          "date": "Thu, 29 Jan 2026 22:23:35 GMT",
          "category": "military conflict",
          "confidence": 0.8308514356613159,
          "weight": 8.30851435661316,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "83.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Trump tells Iran to drop nuclear aims and stop killing protesters to avoid military action",
          "translated_title": "Trump tells Iran to drop nuclear aims and stop killing protesters to avoid military action",
          "link": "https://www.bbc.com/news/articles/c394ymdpjwvo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 14:59:56 GMT",
          "category": "military conflict",
          "confidence": 0.6581318378448486,
          "weight": 6.581318378448486,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "65.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Syria's Kurds sense US betrayal as government forces push them back",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cvgrzd76p4lo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 10:39:58 GMT",
          "category": "political crisis",
          "confidence": 0.9156368970870972,
          "weight": 5.493821382522583,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "91.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "South Africa and Israel expel each other's envoys in diplomatic row",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cvgn8ejljqwo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 16:10:24 GMT",
          "category": "political crisis",
          "confidence": 0.8792426586151123,
          "weight": 5.275455951690674,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "87.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "'I can breathe again' says Israeli hostage held for nearly 500 days in Gaza",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/c8rm20gm364o?at_medium=RSS&at_campaign=rss",
          "date": "Thu, 29 Jan 2026 16:25:40 GMT",
          "category": "violent protest",
          "confidence": 0.5701872706413269,
          "weight": 3.9913108944892883,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "57.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Why Iran's response to a US attack could be different this time",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cn9z497g4vvo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 11:04:11 GMT",
          "category": "terrorist act",
          "confidence": 0.4564652740955353,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Worried families in India urge return of crew on ship seized by Iran",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cdrenj55gdvo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 10:22:47 GMT",
          "category": "political crisis",
          "confidence": 0.4430283308029175,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "44.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "EU adds Iran's Revolutionary Guards to terrorist list",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/c20gypw8enjo?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 01:47:25 GMT",
          "category": "terrorist act",
          "confidence": 0.43389755487442017,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "What could happen if the US strikes Iran? Here are seven scenarios",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/ce3kenge1k9o?at_medium=RSS&at_campaign=rss",
          "date": "Thu, 29 Jan 2026 06:43:49 GMT",
          "category": "military conflict",
          "confidence": 0.4299703538417816,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Inside Syrian camp holding wives and children of suspected IS fighters",
          "translated_title": null,
          "link": "https://www.bbc.com/news/videos/c3ve0xd451go?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 11:38:08 GMT",
          "category": "military conflict",
          "confidence": 0.3512217700481415,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "35.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "UN nuclear watchdog discusses Ukraine nuclear safety risks",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/1/30/un-nuclear-watchdog-discusses-ukraine-nuclear-safety-risks?traffic_source=rss",
          "date": "Fri, 30 Jan 2026 23:02:22 +0000",
          "category": "military conflict",
          "confidence": 0.45773664116859436,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "What do China and the UK want from each other?",
          "translated_title": null,
          "link": "https://www.aljazeera.com/video/inside-story/2026/1/30/what-do-china-and-the-uk-want-from-each-other?traffic_source=rss",
          "date": "Fri, 30 Jan 2026 22:06:20 +0000",
          "category": "violent protest",
          "confidence": 0.30598506331443787,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Iran says ready for ‘fair’ talks with US but not ‘under shadow of threats’",
          "translated_title": null,
          "link": "https://www.aljazeera.com/news/2026/1/30/iran-says-ready-for-fair-talks-with-us-but-not-under-shadow-of-threats?traffic_source=rss",
          "date": "Fri, 30 Jan 2026 21:45:05 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.5907514691352844,
          "weight": -1.1815029382705688,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "59.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Iran"
        },
        {
          "title": "Syrian government reaches deal with Kurdish-led forces",
          "translated_title": null,
          "link": "https://www.bbc.com/news/articles/cz0pj0n0yk3o?at_medium=RSS&at_campaign=rss",
          "date": "Fri, 30 Jan 2026 12:42:37 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.7183884382247925,
          "weight": -1.436776876449585,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "71.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iran"
        }
      ]
    },
    "Iraq": {
      "index": 5.19,
      "raw_score": 29.45,
      "events": [
        {
          "title": "Syrian army declares IS-linked camp 'closed security zone'",
          "translated_title": "Syrian army declares IS-linked camp 'closed security zone'",
          "link": "https://www.newarab.com/news/syrian-army-declares-linked-camp-closed-security-zone",
          "date": "Fri, 30 Jan 2026 17:07:39 +0000",
          "category": "military conflict",
          "confidence": 0.6530262231826782,
          "weight": 6.530262231826782,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "65.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Suspect in Ilhan Omar attack faces federal assault charge",
          "translated_title": "Suspect in Ilhan Omar attack faces federal assault charge",
          "link": "https://www.newarab.com/news/suspect-ilhan-omar-attack-faces-federal-assault-charge",
          "date": "Fri, 30 Jan 2026 16:52:05 +0000",
          "category": "terrorist act",
          "confidence": 0.6715485453605652,
          "weight": 6.043936908245087,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "67.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "UN says Houthi seizure of telecom gear threatens Yemen aid",
          "translated_title": null,
          "link": "https://www.newarab.com/news/un-says-houthi-seizure-telecom-gear-threatens-yemen-aid",
          "date": "Fri, 30 Jan 2026 15:38:47 +0000",
          "category": "political crisis",
          "confidence": 0.7017227411270142,
          "weight": 4.210336446762085,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "70.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Russia suggests Syria has dropped push to prosecute Assad",
          "translated_title": null,
          "link": "https://www.newarab.com/news/russia-suggests-syria-has-dropped-push-prosecute-assad",
          "date": "Fri, 30 Jan 2026 17:26:29 +0000",
          "category": "political crisis",
          "confidence": 0.584617555141449,
          "weight": 3.507705330848694,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "58.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Nationwide protests begin over ICE actions in Minneapolis",
          "translated_title": null,
          "link": "https://www.newarab.com/news/nationwide-protests-begin-over-ice-actions-minneapolis",
          "date": "Fri, 30 Jan 2026 20:15:48 +0000",
          "category": "political crisis",
          "confidence": 0.5750519633293152,
          "weight": 3.450311779975891,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "57.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "US eases Venezuela sanctions after oil sector reforms",
          "translated_title": null,
          "link": "https://www.newarab.com/news/us-eases-venezuela-sanctions-after-oil-sector-reforms",
          "date": "Fri, 30 Jan 2026 19:11:15 +0000",
          "category": "economic crisis",
          "confidence": 0.7568715810775757,
          "weight": 3.0274863243103027,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "75.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "UK activists urge MPs to attend 'rare' debate on Gaza genocide",
          "translated_title": null,
          "link": "https://www.newarab.com/news/uk-activists-urge-mps-attend-rare-debate-gaza-genocide",
          "date": "Fri, 30 Jan 2026 16:57:59 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.8918426036834717,
          "weight": 2.675527811050415,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "89.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Turkey deploys F-16 jets in Somalia",
          "translated_title": null,
          "link": "https://www.newarab.com/news/turkey-deploys-f-16-jets-somalia",
          "date": "Fri, 30 Jan 2026 21:02:56 +0000",
          "category": "military conflict",
          "confidence": 0.44886693358421326,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "44.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Sudanese man jailed in UK for murdering asylum hotel worker",
          "translated_title": null,
          "link": "https://www.newarab.com/news/sudanese-man-jailed-uk-murdering-asylum-hotel-worker",
          "date": "Fri, 30 Jan 2026 20:40:17 +0000",
          "category": "terrorist act",
          "confidence": 0.7761104106903076,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "77.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "US envoys to Israel blocked USAID warnings of Gaza 'wasteland'",
          "translated_title": null,
          "link": "https://www.newarab.com/news/us-envoys-israel-blocked-usaid-warnings-gaza-wasteland",
          "date": "Fri, 30 Jan 2026 17:57:30 +0000",
          "category": "violent protest",
          "confidence": 0.22272494435310364,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Syrian cleric linked to Iran announces new Shia council",
          "translated_title": null,
          "link": "https://www.newarab.com/news/syrian-cleric-linked-iran-announces-new-shia-council",
          "date": "Fri, 30 Jan 2026 16:51:16 +0000",
          "category": "peaceful diplomacy",
          "confidence": 0.18542319536209106,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "18.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Tunisia famed blue-and-white village threatened after rains",
          "translated_title": null,
          "link": "https://www.newarab.com/news/tunisia-famed-blue-and-white-village-threatened-after-rains",
          "date": "Fri, 30 Jan 2026 16:43:45 +0000",
          "category": "humanitarian crisis",
          "confidence": 0.29291224479675293,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Trump threatens tariffs on nations selling oil to Cuba",
          "translated_title": null,
          "link": "https://www.newarab.com/news/trump-threatens-tariffs-nations-selling-oil-cuba",
          "date": "Fri, 30 Jan 2026 16:17:37 +0000",
          "category": "military conflict",
          "confidence": 0.22052133083343506,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "US sanctions against Iran target minister over protesters",
          "translated_title": null,
          "link": "https://www.newarab.com/news/us-sanctions-against-iran-target-minister-over-protesters",
          "date": "Fri, 30 Jan 2026 16:09:07 +0000",
          "category": "political crisis",
          "confidence": 0.43453800678253174,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        },
        {
          "title": "Farage made Dubai trip to woo British expats, meet UAE ministers",
          "translated_title": null,
          "link": "https://www.newarab.com/news/farage-made-dubai-trip-woo-british-expats-meet-uae-ministers",
          "date": "Fri, 30 Jan 2026 15:46:09 +0000",
          "category": "violent protest",
          "confidence": 0.22443926334381104,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Iraq"
        }
      ]
    },
    "Syria": {
      "index": 5.75,
      "raw_score": 43.07,
      "events": [
        {
          "title": "War escalates in north-east Syria as US envoy holds talks in Ankara - thenationalnews.com",
          "translated_title": "War escalates in north-east Syria as US envoy holds talks in Ankara - thenationalnews.com",
          "link": "https://news.google.com/rss/articles/CBMiggFBVV95cUxOUnl6Y1RJOGYxRHNpb1RQZ1k2QUlWaklfWWt0V0d5WHNUNGwzRkI4WEVWak14N2hCcnpWc08tc3dqZ09vNEY4MWpNYWduNHNqSXFyVTlBMFRaY0VOQWkwam5rN0lFNmljMThnd0w5Uk8zTXNNbVRfUlNBQzdjQWNRWEZB?oc=5",
          "date": "Thu, 29 Jan 2026 17:17:15 GMT",
          "category": "military conflict",
          "confidence": 0.9700760245323181,
          "weight": 9.700760245323181,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "97.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Arya Jemo: 'Fifteen years of Syrian civil war to end up with an Al‑Qaeda leader in power' - France 24",
          "translated_title": "Arya Jemo: 'Fifteen years of Syrian civil war to end up with an Al‑Qaeda leader in power' - France 24",
          "link": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQaEFKTlpyMS1uNmRzQTkwaTNxNTlIOUs5NURtUXp0Q1Zkc1JOMHpSYUJuVGlYNVM5eGoxLWRjclVoVVF5R09QUFQ2Qm41a0FBRGl5N3lMMWxaZlc0dGtoWlNEa2xPUXdnN1MzeHRKV1B3NFhKTlYzczkydE1yTExTTVphTExKYVl4dG92TzAxdzhhbjl0a2otV2wxODFLS09TT0ZVa2VRbDVuSzhuVDFZYUcyNC13NnlYTUZyUklEZ3FQcFY4YmJWXzJhSWxINXlIOHE0?oc=5",
          "date": "Fri, 30 Jan 2026 09:17:04 GMT",
          "category": "military conflict",
          "confidence": 0.646390974521637,
          "weight": 6.46390974521637,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "64.6%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Syrian Government and Kurdish-Led Militia Seal a Deal to Merge Forces - The New York Times",
          "translated_title": "Syrian Government and Kurdish-Led Militia Seal a Deal to Merge Forces - The New York Times",
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxQOVlYQUNMSDVMUE5feWtQSGNSaXVfU3BGVkNpVGlYWVRvWlFiejUyRlg4NmJSN2xBOE1EeHEyX1hYV05VOTNfYWt5cUI1N3BiSXVoM3RDOGtZQ1E1ZDhwVnM2Ujlkc0pub3NZR2xwWmNPalhhMnJyVFdsU0drT0Ztckw2Z0o1MEFq?oc=5",
          "date": "Fri, 30 Jan 2026 11:06:36 GMT",
          "category": "military conflict",
          "confidence": 0.6157744526863098,
          "weight": 6.157744526863098,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "61.6%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria's integration deal with SDF to take effect on Monday - TRT World",
          "translated_title": "Syria's integration deal with SDF to take effect on Monday - TRT World",
          "link": "https://news.google.com/rss/articles/CBMiWEFVX3lxTE9mdDlJMFlMQnpWd1VkbDBJUDdyZldDOEV0REZIM242N2RwSHFTRWxFamFwSFlhSUg2MDYwR1B5MmhqNUhfdnZZMkZSS1lZcnlEWWxGRVA5eWnSAV5BVV95cUxPZ0NoNzBRSUMxeHFVLXhmek05Q0toOEMtem9zbWdDSGU5c2RUOTBEaDYydzZFYW5XTy1SWmFfeWxBcHBLZGhmX18ydnR4a3duVWwtYUk1TGtMZm1yR0N3?oc=5",
          "date": "Fri, 30 Jan 2026 23:00:46 GMT",
          "category": "military conflict",
          "confidence": 0.5729315280914307,
          "weight": 5.729315280914307,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "57.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Leveraging The Kurdish National Council And Roj Peshmerga To Break The Deadlock In Syria – Analysis - Eurasia Review",
          "translated_title": "Leveraging The Kurdish National Council And Roj Peshmerga To Break The Deadlock In Syria – Analysis - Eurasia Review",
          "link": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxONlFUMmNVYzluNjV4Y2ZJUGotSllNOUFmQlBkem40R2x0WTFvdnJTTHF5MnhDd1psTEJBRVlXNERXWWtFYUNBV2lSS3hKckZpNnMtN2tza2htN1VXSTNtejctTTBhbXNuRXd6cmxLNzEyNlNkZENYdmY0d2tGalEtMS1FdGQ0d3NBSlZrZ3VYaDJuUjVMMGFLbDFJVEstZW0zbU1vWHZpUG9oSlZRVkNkcVFDWVZEblJBRElHamJ0aV9mUjZhbzZ2ZHFuV3BNa0RDQjZV?oc=5",
          "date": "Thu, 29 Jan 2026 02:18:57 GMT",
          "category": "political crisis",
          "confidence": 0.9505327343940735,
          "weight": 5.703196406364441,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.1%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Syria",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Bipartisan ‘Save the Kurds Act’ introduced to US legislature in response to Rojava conflict - The New Region",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiS0FVX3lxTE5ScXRyUGpjbFNVcTg3amEtMktKTkppXzNyUGEweHNKWFlxcnZlNC1UMC1VdmFsWkU4SjBiVk9SQTdsRmlkbnJlN05aQQ?oc=5",
          "date": "Thu, 29 Jan 2026 18:07:24 GMT",
          "category": "political crisis",
          "confidence": 0.9169758558273315,
          "weight": 5.501855134963989,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "91.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Integration or conflict in northeastern Syria? Ten key points to consider - Middle East Institute",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiowFBVV95cUxNU1U4WVU3U0dXRzladFUxQmFETmRMVHliZlM1YmwtQXRHbnpYWTB4VnpkVjNSRFpRbmhXSlZKdVVlX3dNdGhzRFlVUENhek40N2stTVFZSzFJVjY0NnFoaUNYY0NOY0Q3c2d4RW5XT1NxUVktZHZnQl95Q1V3NlRLUVRmRUhQSkgtN0dNVlVDcDFWdV9qdmJmUVc2YWM1Z2dNQ29n?oc=5",
          "date": "Thu, 29 Jan 2026 16:49:07 GMT",
          "category": "political crisis",
          "confidence": 0.907017171382904,
          "weight": 5.442103028297424,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "90.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Kurds in retreat as US allies switch to backing Syria's new leader - BBC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTE1pMnVhRS1CUkEzanRwMHoxVDhSTE1XanhobTA3SHRwOWo5RTk5Tzd4dlNKbzdMU0pzNnRfTldaRmFxeVRRYmdzWFUtVUJvc0dYWXdfZjUzYXBvZw?oc=5",
          "date": "Fri, 30 Jan 2026 10:39:58 GMT",
          "category": "political crisis",
          "confidence": 0.5350956320762634,
          "weight": 3.2105737924575806,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "53.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "European Ministers: Neglecting Kurdish Rights in Syria Risks Undermining the Fight Against ISIS - kurdistan24.net",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi1AFBVV95cUxOam5zWnZqcDU3RmxSdVNuMXFfdk85UXNKTWJSVUZ2QjBXY2RFbEJnb09FUG1FUGZEeDdPWnF6clBNVVRYMUFycWc5VVBaQlpJY0pQXzcwSXhTYTIyWFRDd3JyZDQ5T3ZiVF9XbXQ1aFpsQkVqVnN5bDZMNXZubEhGWk1IZnBNWUR1aUQ4bXBncENIQTg5aS0wUDExMzE3MTVRM1BKYUt5MUJORDRiWDJ6bFpiNTRNZEI3VnV4VVBHUHQ1Y0hqcnpOR2hPMUN4cjROU2tVYg?oc=5",
          "date": "Fri, 30 Jan 2026 20:38:21 GMT",
          "category": "military conflict",
          "confidence": 0.20961357653141022,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria’s information minister says integration deal with YPG to take effect Monday - Anadolu Ajansı",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMixAFBVV95cUxNeGp6aHpoNXplbUM2Y1hudEFjSDYtZDZFR1JXbHpzN3hudUlpXzgxc3g2b1FEXzdSWHJLcjR1aUlsZkpvTnFTU3hEWkVzUDdHRGp1V0JEWXg1Smd1dWNmbXQxZkdNcmJnNFVtRXpZa2FHQXJjY1h3LXdQZ3kyZlRFWkNKX2xGc1BNVEN5SThpaThQa2lyMUZaTV92ZjVhdTYxb2NndjZ6eDFvNlh0UFFjY0toaUdhdVVCVmFnNWJnUUZrLVc3?oc=5",
          "date": "Fri, 30 Jan 2026 22:20:23 GMT",
          "category": "military conflict",
          "confidence": 0.4392640292644501,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syria to close camps housing thousands linked to Islamic State - Reuters",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirwFBVV95cUxNRzZwcVBQelpMNk92X2k4anZTU1I5Ym94cUJnX1JIYlBtc19HTmhJUTBFc3hrT0ljQVlNcnI0UDdtbkoxTGl3YlpZRl8zLTZKa3Zxc090cXVwOVY3cE5wRE5CLVZ5blFCZktCQTRlRlhCSzFta0NQR2xRUlo1MXl4STh3cGFLQnI4SW9iY19qX3NwZ01NM2E4SmlXbW8waWtqSk5QTXp2Q0RkZE9wSm00?oc=5",
          "date": "Fri, 30 Jan 2026 18:01:32 GMT",
          "category": "military conflict",
          "confidence": 0.2939166724681854,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian government reaches deal with Kurdish forces - BBC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiWkFVX3lxTFAwWW1WcVg3Skp1aUJ6OU43VFlMSVBNQzY3M003alRVNlU1OGlzYVFaQjhpZURIUm5EaHZzR2pHbWVuTENKWE5QSnY3Q3JPSVB2LTlQOWdDc1dndw?oc=5",
          "date": "Fri, 30 Jan 2026 12:42:37 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.4387708902359009,
          "weight": -0.8775417804718018,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "43.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "EU steps up diplomatic and humanitarian efforts in Gaza, Syria, and Sudan - Українські Національні Новини (УНН)",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMimgFBVV95cUxOcTVCU3BwUndvdXNDNFlUWTBGWEk1MVF6OFNpLVkyNTBqbHd3cWgtdkFFWWNqdDNyTW1YYlctOFhRZGVFRlZTNkl6U1hfc2RJcUUxVkhBd3czY0g2S184bzNDOElxS3hJTGZKbERoclcwQXdHV01iN1NiY2Z1c0dfWHBHNW93U1dEQ1pWZHhVaEdCbjljUFQyMkRn0gGYAUFVX3lxTE1YSWhTVG1peWE3YVcwOTV5b216MXltZW1nTjl4aDNwWDNlZ0hqdmZXMHNWdVRhTzBLc1J0amhMaDhscWN3N3pWb3Ntd3d6TWlFeHppc3RRLWdvbE1jeE1kclRZcUtpUnZJNWcyZU1ITGdqVjlVNGdjOVpSOXRXb1NlUWphYjFWOG1LLTFaTk8zTVBjMHZfWXpv?oc=5",
          "date": "Thu, 29 Jan 2026 17:26:34 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5209673643112183,
          "weight": -1.0419347286224365,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "52.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "EU, European states welcome Syria-YPG deal, urge full cessation of hostilities - Anadolu Ajansı",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitgFBVV95cUxOVlpibWpZVUY4ZE9XLUJDdVU0RDhvRTlrZFczUGMwSktTRURnSk1PcDQteXBDdkRsWm5kRkJ4akhFcXVUNmpfWi11T0JoUWphbWxzUGk5Ym1WNElsMFJmRFB0UVdnd0cxdzFFNDlZY0xpSnZLQ3VlVlNLZ0JKVjVULVJBS2lQb0xIbkwya21XTWRWZl9fSWlGN0ozV21ZMzlpS1FsVldyTmp1akU2UVEyMjRtdENxZw?oc=5",
          "date": "Fri, 30 Jan 2026 22:19:19 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5238077640533447,
          "weight": -1.0476155281066895,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "52.4%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Syria"
        },
        {
          "title": "Syrian government and SDF agree ceasefire and integration deal - Middle East Eye",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMingFBVV95cUxNZ2NDQkhiWEY4Y1VidzZXc3RQNVhRTkZDNHc4Ukk3alpkTHVzdXJkbFBOTmFLdWR1SGVoZnppUC0zOVNtbXFvbTUzS1pUdUNZSkxLUUxyWXQzZU1XV2ctWjZKUWVsZTc5R2hSazRJdHZCU3Y4MnZ1eXNraXpZcTg2VWZZSnJWZGFqVTU2SEJ3Q1BzelRwbGdOTWRqV1BRQQ?oc=5",
          "date": "Fri, 30 Jan 2026 09:52:00 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.9349954724311829,
          "weight": -1.8699909448623657,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Syria"
        }
      ]
    },
    "Bulgaria": {
      "index": 1.0,
      "raw_score": 0.0,
      "events": [
        {
          "title": "Public Attitudes and Security Perceptions in Bulgaria: Resilience and Vulnerabilities in 2025 - GLOBSEC",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxPS0FhOGsyNnltZ2tseDFHOEFhN2pYbXNSOVhlNmlHVmpwdzdxOTJnbnFPV1ZEUnY0Q20wSk1ONVROeU0tX2gwMFlnanAtdFlSU01oUU1CaTYxR2JvM0ttWVFQdXYtOGtvYTR1MXhscUdEVVRNeldNcjVERjF2U3lMOEQzWkFUQ2Fz?oc=5",
          "date": "Mon, 26 Jan 2026 07:45:34 GMT",
          "category": "neutral news",
          "confidence": 0.29536062479019165,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria: Borissov and Zhelyazkov Highlight U.S. as Key Ally in Security and Energy Projects - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi0AFBVV95cUxQNDFTOW9kODlsSGlUNmRnd1Fka1NldDkyQU5qcm5yWjBKekRUVm0xalY5aVVIUkNOS2RuaGVtQlpaSm5JU0JydW1XcTVlX0ZOcS1fRHhFVmFFZWQ2Vm5zMGFQRkRPaTRZVENXWjA2U2FnU1BUN2plcGhiLUpOQnY2cl83bkxZSldnR0VMWm9yZm5idFQzMnZ5Q2V3MWNLZC1OdmtlTmVwLTVOdHowSUxyWGFqOW53WTQ0SmtaempXMmdRY2REdzNWUFJFMnRuQW9F?oc=5",
          "date": "Mon, 26 Jan 2026 09:37:14 GMT",
          "category": "neutral news",
          "confidence": 0.25193431973457336,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "25.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria - OSCE.org",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiTkFVX3lxTE5oQXhJQVVCd3Z6ZWxpTzZ2bUZhSjNkMTJ0cURDeFZCY2p2RWxnV04xWnJ0SUVvQkZsRFI5Q3ZWSE5zcmhqMnpfV3R5T1FTZw?oc=5",
          "date": "Fri, 28 Nov 2025 15:31:15 GMT",
          "category": "neutral news",
          "confidence": 0.2624431550502777,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "26.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria will participate in all areas in which it has the capacity to contribute to pan-European security, said the Bulgarian Prime Minister - European Newsroom",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxNTEc3VjlMbnIyR3F3Q0xlUS1IbzhtSk9fcWVYd1JsUzBBUHhGaDdpSURINjZyX1FNY010SE1yWkF4RjN6UXFGS2pNVUlCS091NGwwZHM4emU0a2JLdko5X3llSXI2THI2ZkVkakZpU2h2RUZwSjFwNElzWVluV1ZTTGV0aFQ1TVdfLUxBZEdmVTBXaWZ0WjNQc0hUZnVoUmpNS0tsOVNyMmdHVmZKZXF3R2EwNm9VWG4tVFhSc3lqMGFNd0dLMjRaZld6YmRObDBNU29nOUNESWdicmNhdGdMckZxXzdoYkJ0OWJsUXRjVmRYT19ZUFU5MEY4NXdNN2s?oc=5",
          "date": "Wed, 07 Jan 2026 14:48:19 GMT",
          "category": "neutral news",
          "confidence": 0.45812496542930603,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria - Welcome to the United Nations",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiT0FVX3lxTFB0OV9ZQXgwS1JkblpabXNoNExTbXlobXZ6S19UMXlmOGVSdWdkR2NlSzFBcmRfak11eFNvX0t5dTRrSXpnWlFKY1JwUlhqaFk?oc=5",
          "date": "Fri, 26 Sep 2025 07:00:00 GMT",
          "category": "neutral news",
          "confidence": 0.21918389201164246,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria is set to select its Vienna 2026 artist - eurovision.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMid0FVX3lxTE5UVFR6aEpYTU1ZMU1mem9udU1jTE9EbEtwQjlVTmJzTXZSTnFhUXF5VEctdHNXc0dZWUdrMFhUek53c0ZkQUprTU9NZzZvRVNodzVZdnhHVlN3SEhfRmJCYmZjbFJYWUppaUpPYVBNVXdabUEtZlB3?oc=5",
          "date": "Fri, 30 Jan 2026 16:36:51 GMT",
          "category": "violent protest",
          "confidence": 0.2731146514415741,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "27.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "EC opens seven new infringement cases against Bulgaria - The Sofia Globe",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNTlp1bmE5a3JDYWpHUE9BYmQ1RlBuaG55TnJiOTZFMkQ2c05ibkU4R19TY0pwTzlqZjlhcE5sWnVYZDFvSkdoemJXeU5GWDZGelB2ZDluSXFBTFB3V0Z6STROSFpXV3JZM3NnNmltYXV4OE9sUFJWdVpYTjFxc1hEYUFHOHgtRWVlQXlpRWMtVnd2Q0U?oc=5",
          "date": "Fri, 30 Jan 2026 12:53:19 GMT",
          "category": "neutral news",
          "confidence": 0.21752437949180603,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Large migrant smuggling operation in Bulgaria leads to 16 arrests - Europol",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMivgFBVV95cUxOc0U5Unk3SGFEMXQxWlRhbnVvMmNHaVpEbE8tNjh3U3FFUlcxOXdFLWJDNkVPTWk2QUJjN0NsWFN4RW1SZGRxN090WURCbkJXcjN6OE1iZ1FtZENzRXU0YlpPdzdIYnRYanE0b1hqWnJXZldUajFRc3N5RTBRLUFBd1FzYlU2VEd6bk4yQmdZaXdrWnV2NDBmZ05ITTRDUW9FTDlfdUJyRE9NZ2Y3d2FkQ3BJQUlYRXZVVW5UV3p3?oc=5",
          "date": "Thu, 29 Jan 2026 15:20:25 GMT",
          "category": "terrorist act",
          "confidence": 0.24750301241874695,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.8%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Wizz Air Expands Operations in Bulgaria with Eighth Aircraft in Sofia and Five New Routes - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiygFBVV95cUxPME41azl2Wnd4bERSc1RUS3M0eU9rdURjMVc3eFE2RDlNMnpTanFCTDBpNGdQdHM1eTluMUZBZ3NaRjhxT0NPWkZzZGdGUll2OUcxNDVIZlNyZm5RQU14TTRON1VYRk5EYWdvYVNjUzFBV1NzcHJEUW5sNTBKR3EtVTk2TW9xZjdTWl8yT1p5djh0Yll6NEF1VnYxc1JQVUkxOFNqdEFrR3FVOUpEcF9tVXZNLTJKLWxXcnhCNUdFZjZ6LXhJNGQxTnJR?oc=5",
          "date": "Fri, 30 Jan 2026 16:10:59 GMT",
          "category": "violent protest",
          "confidence": 0.2486225813627243,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "🇧🇬 Bulgaria: AIDAN & Alis Among Guests for Natsionalnata Selektsiya 2026 Artist Final - Eurovoix",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqgFBVV95cUxNX3plUERrbzNUcm1mZGtOUXg2ci1vRzExYzV6VW5mQXR4Y3N5blBGNDhnWk0zY3hLaThnRnJmMHRWbjYyalVHNWFWOVdRWXZlakZtV3dhM3FrZGthTUxUanRZSGNZVkF5bGN2VUhrNDVveVBhX1JMSUJNcDJFZXp2cWJBSEVuU2JvNjNEczVMNkJVTjA1Z0c0TWFFMEpNM0Y4T3dZa3F2Vkg3UQ?oc=5",
          "date": "Thu, 29 Jan 2026 19:28:36 GMT",
          "category": "violent protest",
          "confidence": 0.337433397769928,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "33.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgarian Torrent Giants Zamunda, Zelka, and ArenaBG Seized in Joint U.S.-Bulgarian Operation - torrentfreak.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMitwFBVV95cUxNUEhUMmNOYlY3b3hubkpwRGJSaXdxenNicUlJQnRGZXpSaFdsNklQSUVfRGdBY0hkZGg1MGs4ajFELS04VFRXeFhXRmJ1aGJVYjlHS01CdVR4ZzFwaG9BX1hrMGV0akQ0Ql9ZNzFGNmctY1V4dDFWZ05MeURfUW9PYUhDX2ctZWUtcnhNSEQ3U1pndzR0US1tR1E1c1FJUk1lR29QYlJnSndNQ01ibnNHUUd3eXRpNnM?oc=5",
          "date": "Fri, 30 Jan 2026 02:15:00 GMT",
          "category": "violent protest",
          "confidence": 0.29994839429855347,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.0%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria’s Maria Gabriel appointed assistant director-general of Unesco - The Sofia Globe",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxNdUJ6VkJsYkRNbTh3TkZSZVhXZHB6SndUcXctVGZkanRCNDhJLUJxampMb2JnbjRhV05JaThac2xpaFR5MjhDUHNudUJUYmY0dUhRdEM0bmliTTZ3eFNGcEQydzluM1pvSEFBYXBwbm5iMXJhOXFrZmZkWWN0QW12MTFFRGdJb2RHN0hscWtTSDdzZFpfLUVyczhhdjF5elZlcFdCQS0tcXc?oc=5",
          "date": "Fri, 30 Jan 2026 17:15:11 GMT",
          "category": "violent protest",
          "confidence": 0.29073283076286316,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "29.1%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Eurostat: 3.3% Unemployment in Bulgaria in December 2025 - The Sofia Globe",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMikwFBVV95cUxNM25zczJsNVFkQmx4ejZNZEozTWFxN3N6VUNqb1VEMDJaUW1RNmpFZUFlQllQYnZmb2xnUWhSTFBtYnNQLUFHQjc4R3ljX1loR04wVzdYQUxYcHZpUjNzUTRnOG9VNjNwcnFPOHVRRERSMzFRTTZndzZadkJRMnBRZy1EYzEwZVdJbDl5TklBNkdDc3M?oc=5",
          "date": "Fri, 30 Jan 2026 10:07:12 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.2237420231103897,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.4%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Poll finds sharp improvement in business sentiment in Bulgaria in January - The Sofia Globe",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirAFBVV95cUxQT1ZibDlqbmdSbnp3YmJ5UWFFNjNkbWpCOGdNc0oxdEh3b0xUX3RhSHlYUGM4cF82dlZscTRyWXFDeTdRNFlGcFlQMXJGX0pnYzRDTW9pX3NpOUZ2Z0Q0QzdoUkVtQVJHMTJYY00zeXdQZXBUcHEzWW1rLXczbTFHYnFTUnZPZVktd1BiOXpkanhZRjRtWXdoWF9ORE4tWXByQ3R1b0hCalpSVWdC?oc=5",
          "date": "Fri, 30 Jan 2026 09:14:45 GMT",
          "category": "neutral news",
          "confidence": 0.4253201484680176,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        },
        {
          "title": "Bulgaria Prepares To Notify Europe On State Aid Plans For New Nuclear Plants At Kozloduy - NucNet",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiwwFBVV95cUxQTmFrWHoydENiSThiX3hKY05sQmlvUHB4bkhIWHdET0dGVFdqNWFUQlFSSDA4TW1KdUFFSlNHbld2MmV1ZGYydDFfNUdXMnN4bF9nbEtZU2ZRQ1l0dWxwMmk3N1p0VWpVSWtuS04tN2NGOUREWUZzOWUzSWlDOHAwS2dxeGNDZkhzRzNBR05TenRRRF92cWlpeEljZEJzdmpFdk91UU8tWXFXbTJsS1pWUk9OLUpBZjMxdkVJc2x2bDVQX28?oc=5",
          "date": "Fri, 30 Jan 2026 15:09:39 GMT",
          "category": "military conflict",
          "confidence": 0.3021392524242401,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "30.2%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Bulgaria"
        }
      ]
    },
    "Turkey": {
      "index": 5.31,
      "raw_score": 31.86,
      "events": [
        {
          "title": "Balkan truckers choke EU borders over entry-exit rules - Türkiye Today",
          "translated_title": "Balkan truckers choke EU borders over entry-exit rules - Türkiye Today",
          "link": "https://news.google.com/rss/articles/CBMinwFBVV95cUxOellzZGZBOHowWG90dERMVHZCeEZZSVlRSUV6VmN3WnJ2czNHNjRrV3lFMWJnYXNXR2VURFIwUndwODBlM2FiWlF2Y1U1amw0ZXNhRVJYdlV0aXBrQ25sLXE0Y1EyejVxUU11MWRKYkthSjRxeWRtUVFNUW8wYXZHY21MNDVUSEItM3l0RFNDLXhmeklCODVLMW5NLWRpaFk?oc=5",
          "date": "Thu, 29 Jan 2026 09:04:11 GMT",
          "category": "violent protest",
          "confidence": 0.939254879951477,
          "weight": 6.574784159660339,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.9%",
          "detected_lang": "local",
          "is_translated": true,
          "country": "Turkey",
          "translation_engine": "Google Neural MT"
        },
        {
          "title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - Community Newspaper Group",
          "translated_title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - Community Newspaper Group",
          "link": "https://news.google.com/rss/articles/CBMi_wFBVV95cUxQeHVldlpQLVBlRVR3clI0VDRUbVExU2VDQnJiNVZkYW5iVTNYd3Q2R2tuSjRiM0RjQUtqUDk0QkRFUmt2YWpleDJ3NVRBNVhRNFZKd2Vvd1NmaGk2bUJFdFVwZ0tURWFDaWFrRE9VaW8tY3JKRFByZTNRZlc1S1VCQk1jX3pGenZabEo3YTBZbk9NUElxcGRLX1BPTG9KeVc3cGRiMzJWS2p3Tjh4MDZjRDhHdTF0V0hRaG5hakhIdjdMaS0tU1MwdFdxam9kMGJ4eXBJalhwYUxlbFh2RGJFMm5ENU56SkYxT0p5eUplU29ab0tqeW5aRUd0VDNxYTA?oc=5",
          "date": "Thu, 29 Jan 2026 11:37:37 GMT",
          "category": "political crisis",
          "confidence": 0.950854480266571,
          "weight": 5.705126881599426,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - Shelby News",
          "translated_title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - Shelby News",
          "link": "https://news.google.com/rss/articles/CBMi8AFBVV95cUxQdzB6dlNFU2o3azNQTHp2ODczZjU3d3VQVUpYZHV5NWh3OXdadzU2c1o3ZUpLMkFxcGkwQi1tYzZYWGEzb2hRTFg0QktfUjZsaFNaeXN2SE9BZnlrQmNuVXoxcFdkVkFWUk1mZnY3Z3UzeFBPSmhmQ21iblNjbEM0WXhBV1RRMWRPaS0xR0JqOHlLSTM4TXVlNWUxZTNaSmRlWndfSGxpN01pVkp3eHpOOTM5Q3hZVDNoRDhXSG1sbFAxMjJuZk9JME9na3ZZWWRyd3FfYmkwVDk2aWdfVW1kZDI3aFdFc0dvQWJzOHlpSnU?oc=5",
          "date": "Thu, 29 Jan 2026 10:27:15 GMT",
          "category": "political crisis",
          "confidence": 0.9505389928817749,
          "weight": 5.703233957290649,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "95.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - The Straits Times",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMixAFBVV95cUxQZEJmOFAxWTNRT3RGaGJVdDZaRTQ4bGxYQ3BLZUdXMFVIbXZTMDYydlpQRkpHbk1VMUJVWGoyZnFGc0RaRElyVlFRNzRRV0FYZldkQS14YVJMWUdkV2E5bGdBeldobldLTHVjVkY4eGFHTTJqdE1lREViRllrRExoZDhQVWRzZ2JTakQtdU5ULXJXLVpyU3l0QzFJc2dWZGVWenJzbmFXWlBRMnlXd05GZWJCazF1Q19DTTh0NHMxbERDbll5?oc=5",
          "date": "Thu, 29 Jan 2026 09:35:00 GMT",
          "category": "political crisis",
          "confidence": 0.9371132850646973,
          "weight": 5.622679710388184,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.7%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey to offer mediation on US-Iran tensions, weighs border measures - France 24",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiwAFBVV95cUxQRFBQb2c2NmxUQmJhNldnR1A5eUIzdFBEN0o2YWl0a2lOckJ5QTdhMVZvMDVScDlSTFJGbkVUUUpZMHloWFZnT3F2N3FnR2tqUHpMQTBZeG1EMHVlVEpwUU1iVHJMTFpQWVlfbkdPdVlERndpR1RmYjVaN29PTDEyRlI5VXdaclVtN01ZZERaWWt1bmZ1aUFMYzRaU2haUHFHdUdlYjExNmY4QnVZZm1uVzU1T2dDdEVFUEI3RENUMXc?oc=5",
          "date": "Thu, 29 Jan 2026 09:49:15 GMT",
          "category": "political crisis",
          "confidence": 0.9327064156532288,
          "weight": 5.596238493919373,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "93.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "'People's Caravan' detained on Greece-Turkey border - Bianet",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiiAFBVV95cUxNSkxDZmk0WDhkOTdCSVVwMmE3Zmp2aERwOWdBdFVKS1FQQkZNcHBuNlQ4TDVuWlVfTld5SF9kY2FFMkRXdzZKQW5YTG9XUUJPQzlMNmtBblZrTkotTHJlYW83ckpJV3EwVU1wb2dmajZEZUlIYmdjbDUweUVJNTJWWFpud2d1R0li?oc=5",
          "date": "Thu, 29 Jan 2026 09:29:00 GMT",
          "category": "violent protest",
          "confidence": 0.5247902274131775,
          "weight": 3.6735315918922424,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "52.5%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Türkiye is Bracing Itself for War and Massive Migration of Iranians - IranWire",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiogFBVV95cUxOT1E5YmtVZExWUndSdG5Iellwc1Y2c2pfMTY4VFdhbnpoRWExY3JPNWZxbVota1VGd1VITGc3R0R6c2F2S2ZRRUFkNHN1RWYteFRJUU80U3l0Zk1yVXliRS1pWDdJcGRmQ2VoZDhicHhONjhFQlhMNjY2VlJJT1MyWHpfa0RmMmlNZkdPOWkyY21zSGFjM3Y3UGU1Q0tiSXhFWmc?oc=5",
          "date": "Fri, 30 Jan 2026 15:33:57 GMT",
          "category": "violent protest",
          "confidence": 0.23256143927574158,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "23.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey plans to reinforce border security if US attacks Iran - Turkish Minute",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipAFBVV95cUxQRmFPODlxVzR2clF3WEE5R3RXOWJBeE1zQ0FsOHV0dGVmcjZVM1lDYzJRQVZ2MzR6YlBIcV9GTWl5Tmg0OXVtZGM2UThJSFdWVG1JZldqZk53WmlsUEVhQm9ITnpEaThmVHZVMENmVjBIYnloMjdjcFByeFpSVHBWWk5MbDRGODFQVUhha1d1ckc2UERXS2ZDcEVaU0JmRW9nNmFwMtIBqgFBVV95cUxQdFRnQ2cxNmY1d25iWV9wZmpQZ1pFdno1dnUwSHhPd0lCYk5jV0ZSQTgyX2twZDZKMHAzdC1tQTg1SGVYX1Iwc3ZSWkEwaG5pYm11NUdLQWJmZEgzQzlXaHVURFFRTXBQeVRnLXdJZWpTVk4tRG43b3RYQW9UbU1qbjh5eHBUa09VMkpENWdPX1VnT0wzYXVTMjA4dzhOVEg2NTg0bW1ybDFGZw?oc=5",
          "date": "Thu, 29 Jan 2026 09:19:19 GMT",
          "category": "military conflict",
          "confidence": 0.45316216349601746,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "45.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Bulgaria, Türkiye plan for new border crossing - Hürriyet Daily News",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMijwFBVV95cUxPYms2N2YzdG95UDFRaHZaOThSYUtMUXplazNraTVDZ21GdlBUdklUQmFlZmtweTg3LUNyME1GdDBabVBiV1NMdkF0M1ROZDVzNDRzY01IWDNzSTNFbkhWR1l1TXFpdTJqSndrZFNEbnRQU1ZReGNEOU9tTE9wTjNqZkV6bXVRR3VEMU03Q2Utb9IBlAFBVV95cUxQTVIta2dBZjVxRWVHc1RnSUpPcXFWcE96UDdndFQ4VE9CdkpyZXRjUzVoaUFyTFhpeC13c1BLeHNwMEZneG1GVjM0cjEzbnp1NFFMSloyR29vTGY5dDZBek1LbTMyOEZMeUwtaWd4Q0VBOUtqSUZNaWdDOWhGN29US2YtVHp3d21vNTVGSzY2ZEMzYndL?oc=5",
          "date": "Thu, 29 Jan 2026 23:47:24 GMT",
          "category": "neutral news",
          "confidence": 0.21624279022216797,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "21.6%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Türkiye prepares for worst along borders if US strikes Iran - Türkiye Today",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMipgFBVV95cUxONHRWMnJBYXZLSzFJdE41d0o5WkxMQk9lMEl5bEhubFlYUnpfR0JDSTdBaVNvc2dPNHBjaU12TTIzWkgxRm02VG5DOHd2dG5vUklDY3Q0dUdkT3E2aURCcXdPXzhQY2lPQlFEeDBpaVFRUzhJRkxMc1RkaHpNSTJsQkM5aENzS3hScHo1VE0zeDRoc3hpb09QOEFWaEVGM0F3WGtzYWtB?oc=5",
          "date": "Thu, 29 Jan 2026 13:09:42 GMT",
          "category": "military conflict",
          "confidence": 0.49263593554496765,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "49.3%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Bulgaria to Open New Joint Border Checkpoints with Serbia and Turkey - Novinite.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMirgFBVV95cUxQdnY1bTdCS2lMS0pIeGZqYktnS3ItbFRTNnpVUjFSM1p4aXJ0RkJZd3pZRWFydTBrdUV2S1dHdGt3NGRyQmZLdzhwc1d1eklkdUEtcjZDUW5UOUt0dlAyZm1UTm9TNzJEaXlSNGx5ejRuNmthc0pja2dESmhFUHBYc1E5bTdEQ0lsUWJoaVFGOUc2cGw0dG9qVk9BWExqNlRGVG1uMGJGN3FWcmxfQUE?oc=5",
          "date": "Fri, 30 Jan 2026 12:22:30 GMT",
          "category": "violent protest",
          "confidence": 0.22319498658180237,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "22.3%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey plans to ‘reinforce border security’ if US attacks Iran and regime falls, official says - The Times of Israel",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi0wFBVV95cUxQekozR2UxSW9lSFdSbFh2bXB5VHVlZVpsWnNBV1ZYUktudldzb1RiMlVpQ0IyZzlQbnRMeWQ3V2dkV3JYcHVyb0VpZWNNYjgyT1BqSWhVZU9XSzZGRnFNRVpNMl9sYmliLURxM1d5Z1VVWllyb2FwalB4YUUwQjlXanJHVk5BZXhRcjJCYkRiWG1leHpFVVVRSVFKWlZWak0xWnl5MlpKVDVtN0prZHZFR0VKRWZyUXE1c01HR1ZzYmkzS3ZYaVh2VF9nNzlWX3RwczZj?oc=5",
          "date": "Thu, 29 Jan 2026 08:49:00 GMT",
          "category": "political crisis",
          "confidence": 0.4265022873878479,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "42.7%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "women's initiative in Turkey calls for end to attacks on Rojava, opening of Kobani border crossing - ANHA",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMivgFBVV95cUxPSnV2NTFVOE5CLXFtZjdUa3NFMGlBak5NTFNlTDYzeHlXTmtHcVlTWkFHbUlIQWRxdzRkcWNqV0EtMC1DdlN3dTYzb2ExQS1VU1haVlBycEEtNkd1M2lDbTBkVGM2Xy1kLU9DZ2xNak5tdnhZS0JoNDFGVXpYbjQ5SVF1UzRaV0Z0d051XzFGYVhvVVZqS1FORDBTdU5GOFU2LWE1TnNLTHJyZHdPdUdab0YwRURUS2hpYVlxRjZ3?oc=5",
          "date": "Thu, 29 Jan 2026 13:59:24 GMT",
          "category": "military conflict",
          "confidence": 0.34111568331718445,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "34.1%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Turkey plans to bolster its border security with Iran - IslanderNews.com",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMi3AFBVV95cUxNekZoWlVQbTluekN0YUxwdzllVnJRY0RndUR2YXRFYjJTNFdoYkRjWFZpUnJ1Z21jSFlsNm92amMyQ3B1aXY0M3dqVTdicDQtb3U5NVRFTnN2aGVRVXVNVVFWTmN1SlFWa3U5bGo0VkoweHktMEN2eG5taG1tdElfM2U3TGtoMkQ2SGpfZzVjS0R5VEx2ZklrSjhWQ0dmZGhBN2ljNW1CdEFRX3VkNm1XQ0xzQzZubElZbDdfMUJUWjR6aEV1LXg2NlkxcXJ3bWRpdHZwSXJUc1RfcklE?oc=5",
          "date": "Thu, 29 Jan 2026 11:05:14 GMT",
          "category": "violent protest",
          "confidence": 0.24920059740543365,
          "weight": 0.0,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "24.9%",
          "detected_lang": "en",
          "is_translated": false,
          "country": "Turkey"
        },
        {
          "title": "Türkiye restructures border gates with Syria in cooperation push | Daily Sabah - Daily Sabah",
          "translated_title": null,
          "link": "https://news.google.com/rss/articles/CBMiqAFBVV95cUxQRHVyZHM2SHZ0X3l4QzRsWW50UFFfZ2I2NlFQVDBBYnBUb043RmVFdTFNWlhFakkyTkpQeFRQWDFxM2lYR1FrVGswbEFSUW50T2hqUTFhVk1tSWR1R3l4MFpFY2psLTBvRlJpaTlHa3VFenQxQUdSOW1qRURHalNaQ0ZMbFp3RFlaZ21hdEVSLU5DbnJnUms2cEdxMFBBWEVLTWFXVEZpYjPSAa4BQVVfeXFMTTMwa2N4RDYtYThZbGR1aDl0NGg4eFdidDNSUklKWEpoS0pvY05Ba1oxT2RxbDlSWFY2WjdjR3JfZXg5ZnBLc19VbGh0SzFKN19tR2R5YlFHUWdUZGJjVkN6VkhUUEhYM0tSV29Kdm9nZ3VCc2dPQVZUUS1oa0xwRU04dnV3TnpCeEpqY0ZxOWYtcXktMm1sZ3B6V1NERU9sd0FQTi1tekVUYkhVOVRR?oc=5",
          "date": "Fri, 30 Jan 2026 11:18:34 GMT",
          "category": "peaceful diplomacy",
          "confidence": 0.5089522004127502,
          "weight": -1.0179044008255005,
          "ai_model": "XLM-RoBERTa-Large-XNLI",
          "ai_confidence_score": "50.9%",
          "detected_lang": "local",
          "is_translated": false,
          "country": "Turkey"
        }
      ]
    }
  },
  "history": [
    {
      "timestamp": "2026-01-28T23:45:58.269589",
      "main_index": 7.99,
      "index": 7.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T02:05:09.998466",
      "main_index": 7.72,
      "index": 7.72,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T04:19:51.519501",
      "main_index": 7.88,
      "index": 7.88,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T05:53:57.545449",
      "main_index": 7.95,
      "index": 7.95,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T07:01:37.443452",
      "main_index": 7.85,
      "index": 7.85,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T08:01:14.358050",
      "main_index": 7.61,
      "index": 7.61,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T08:58:36.485704",
      "main_index": 7.73,
      "index": 7.73,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T10:03:56.878262",
      "main_index": 7.78,
      "index": 7.78,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T10:57:02.430786",
      "main_index": 7.96,
      "index": 7.96,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T11:52:32.218552",
      "main_index": 7.76,
      "index": 7.76,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T13:13:35.250985",
      "main_index": 7.75,
      "index": 7.75,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T14:21:06.050159",
      "main_index": 7.76,
      "index": 7.76,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T15:09:36.554202",
      "main_index": 7.74,
      "index": 7.74,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T15:55:36.042791",
      "main_index": 7.88,
      "index": 7.88,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T16:56:30.474707",
      "main_index": 8.3,
      "index": 8.3,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T17:51:12.540712",
      "main_index": 7.96,
      "index": 7.96,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T18:54:56.754502",
      "main_index": 7.75,
      "index": 7.75,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T19:44:20.095213",
      "main_index": 8.16,
      "index": 8.16,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T20:48:13.810806",
      "main_index": 7.77,
      "index": 7.77,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T21:37:25.429374",
      "main_index": 7.87,
      "index": 7.87,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T22:38:02.033426",
      "main_index": 7.7,
      "index": 7.7,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-29T23:36:34.067518",
      "main_index": 8.05,
      "index": 8.05,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T02:13:31.605268",
      "main_index": 7.9,
      "index": 7.9,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T04:21:31.607236",
      "main_index": 7.99,
      "index": 7.99,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T05:56:30.727194",
      "main_index": 8.13,
      "index": 8.13,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T06:57:32.740218",
      "main_index": 7.91,
      "index": 7.91,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T07:52:05.431395",
      "main_index": 7.78,
      "index": 7.78,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T08:47:51.055876",
      "main_index": 7.92,
      "index": 7.92,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T09:49:17.055302",
      "main_index": 7.89,
      "index": 7.89,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T10:47:18.643738",
      "main_index": 8.02,
      "index": 8.02,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T11:40:49.775778",
      "main_index": 8.14,
      "index": 8.14,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T13:04:04.136607",
      "main_index": 8.25,
      "index": 8.25,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T14:16:30.618876",
      "main_index": 7.95,
      "index": 7.95,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T14:47:43.867227",
      "main_index": 8.16,
      "index": 8.16,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T15:54:16.392422",
      "main_index": 7.68,
      "index": 7.68,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T16:56:37.538128",
      "main_index": 7.8,
      "index": 7.8,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T17:42:02.401956",
      "main_index": 8.18,
      "index": 8.18,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T18:53:02.955570",
      "main_index": 7.97,
      "index": 7.97,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T19:45:12.935904",
      "main_index": 7.85,
      "index": 7.85,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T20:40:23.037604",
      "main_index": 8.02,
      "index": 8.02,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T21:38:12.025729",
      "main_index": 8.06,
      "index": 8.06,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T22:40:58.890548",
      "main_index": 7.88,
      "index": 7.88,
      "type": "historical"
    },
    {
      "timestamp": "2026-01-30T23:36:28.687576",
      "main_index": 7.94,
      "index": 7.94,
      "type": "historical"
    }
  ],
  "forecast": [
    {
      "timestamp": "2026-01-31T00:36:28.687576",
      "index": 7.99,
      "main_index": 7.99,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-31T01:36:28.687576",
      "index": 8.0,
      "main_index": 8.0,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-31T02:36:28.687576",
      "index": 8.0,
      "main_index": 8.0,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-31T03:36:28.687576",
      "index": 8.0,
      "main_index": 8.0,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-31T04:36:28.687576",
      "index": 8.0,
      "main_index": 8.0,
      "confidence": 0.3,
      "type": "forecast"
    },
    {
      "timestamp": "2026-01-31T05:36:28.687576",
      "index": 8.01,
      "main_index": 8.01,
      "confidence": 0.3,
      "type": "forecast"
    }
  ],
  "methodology": {
    "name": "Modified Goldstein Scale",
    "description": "AI-powered threat classification using XLM-RoBERTa multilingual model with category-weighted scoring",
    "weights": {
      "military conflict": 10.0,
      "terrorist act": 9.0,
      "violent protest": 7.0,
      "political crisis": 6.0,
      "economic crisis": 4.0,
      "humanitarian crisis": 3.0,
      "peaceful diplomacy": -2.0,
      "neutral news": 0.0
    },
    "formula": "ThreatIndex = log10(1 + sum(category_weight * confidence)) * 3.5",
    "scale": {
      "min": 1.0,
      "max": 10.0,
      "thresholds": {
        "STABLE": [
          1.0,
          4.0
        ],
        "ELEVATED": [
          4.0,
          7.0
        ],
        "CRITICAL": [
          7.0,
          10.0
        ]
      }
    }
  }
};